import { estimateVehicle, simulationResult } from './engines.js';

export class AdapterError extends Error{constructor(message,{type='platform_failure',retryable=true}={}){super(message);this.type=type;this.retryable=retryable}}
class BaseAdapter{constructor(id,capabilities){this.id=id;this.capabilities=capabilities;this.mode='deterministic-mvp'}describe(){return{id:this.id,capabilities:this.capabilities,mode:this.mode,status:'ready'}}}
class CadAdapter extends BaseAdapter{constructor(){super('cad.parametric',['package.generate','cad.measure','cad.export.step'])}async execute(action,input){if(!this.capabilities.includes(action))throw new AdapterError(`Unsupported CAD action: ${action}`,{retryable:false});const p=input.parameters||{};return{artifactId:`CAD-${Date.now()}`,format:action==='cad.export.step'?'STEP':'PARAMETRIC_JSON',parameters:p,bounds:{length:p.length||3990,width:p.width||1810,height:p.height||1570},checksum:`mvp-${Object.values(p).join('-')}`}}}
class SimulationAdapter extends BaseAdapter{constructor(){super('simulation.multiphysics',['simulation.fast','simulation.aero','simulation.thermal','simulation.structure','simulation.range'])}async execute(action,input){const type=action.split('.')[1];if(!this.capabilities.includes(action))throw new AdapterError(`Unsupported simulation: ${action}`,{retryable:false});const metrics=input.metrics||estimateVehicle(input.parameters||{});return{runId:`SIM-${Date.now()}`,fidelity:type==='fast'?'low':'medium',result:type==='fast'?metrics:simulationResult(type,metrics),evidence:{confidence:type==='fast'?.78:.9,modelVersion:'mvp-1'}}}}
class ManufacturingAdapter extends BaseAdapter{constructor(){super('manufacturing.rules',['manufacturing.check','cost.rollup'])}async execute(action,input){if(action==='cost.rollup')return{cost:input.metrics?.cost||28.6,currency:'M KRW',confidence:.9};const p=input.parameters||{};const violations=[];if((p.length||3990)>4000)violations.push({rule:'DIM-LENGTH-001',severity:'must',message:'전장 4,000 mm 초과'});return{manufacturable:violations.length===0,violations,confidence:.86}}}
class RobotAdapter extends BaseAdapter{constructor(){super('robot.ros2',['robot.prototype','robot.test'])}async execute(action,input){if(!input.approval||input.approval.grade!=='S4'||input.approval.status!=='approved')throw new AdapterError('S4 현장 책임자 승인 필요',{type:'safety_failure',retryable:false});if(!input.interlocks?.emergencyStop||!input.interlocks?.cellClear)throw new AdapterError('물리 인터록 확인 실패',{type:'safety_failure',retryable:false});return{commandId:`ROS-ACTION-${Date.now()}`,action,status:'accepted',dryRun:true,note:'실제 ROS 2 Gateway 연결 전 결정론적 안전 모드'}}}
export class AdapterRegistry{constructor(){this.adapters=new Map();[new CadAdapter(),new SimulationAdapter(),new ManufacturingAdapter(),new RobotAdapter()].forEach(a=>this.adapters.set(a.id,a))}list(){return[...this.adapters.values()].map(a=>a.describe())}get(id){const a=this.adapters.get(id);if(!a)throw new AdapterError(`Adapter not found: ${id}`,{retryable:false});return a}execute(id,action,input){return this.get(id).execute(action,input)}}
