import { randomUUID } from 'node:crypto';

export const agentRoles=['chief_architect','style','package','body','aero','battery','chassis','electrical','software','manufacturing','safety','quality','adversarial_reviewer','evidence','robot'];
export const agentTools=['requirements.read','requirements.write','design.graph','cad.parameters','package.solve','simulation.aero','simulation.thermal','simulation.structure','simulation.range','bom.read','cost.estimate','safety.review','evidence.read','approval.request','robot.execute'];
const clean=(value,max=100)=>String(value||'').trim().slice(0,max);
export function validateAgent(input,{partial=false}={}){const result={};if(!partial||input.name!==undefined){result.name=clean(input.name);if(!result.name)throw failure('agent_name_required')}if(!partial||input.role!==undefined){result.role=clean(input.role,40);if(!agentRoles.includes(result.role))throw failure('agent_role_invalid')}if(input.modelRef!==undefined||!partial)result.modelRef=clean(input.modelRef||'engineering-agent-v1',80);if(input.promptVersion!==undefined||!partial)result.promptVersion=clean(input.promptVersion||'1.0.0',32);if(input.tools!==undefined||!partial){if(!Array.isArray(input.tools))throw failure('agent_tools_invalid');result.tools=[...new Set(input.tools)];const invalid=result.tools.filter(x=>!agentTools.includes(x));if(invalid.length)throw failure('agent_tool_not_allowed',{invalid})}if(input.canGenerate!==undefined||!partial)result.canGenerate=Boolean(input.canGenerate);if(input.canReview!==undefined||!partial)result.canReview=Boolean(input.canReview);if((result.canGenerate??input.canGenerate)&&(result.canReview??input.canReview))throw failure('agent_separation_of_duties');if(input.enabled!==undefined||!partial)result.enabled=input.enabled!==false;return result}
export function createAgent(db,input,{organizationId,actor}){const values=validateAgent(input),agent={id:`AGENT-${randomUUID().slice(0,8)}`,organizationId,status:'idle',...values,createdBy:actor,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.agents.push(agent);return agent}
export function updateAgent(agent,patch,{actor}){const values=validateAgent({...agent,...patch},{partial:true});if((values.canGenerate??agent.canGenerate)&&(values.canReview??agent.canReview))throw failure('agent_separation_of_duties');Object.assign(agent,values,{updatedBy:actor,updatedAt:new Date().toISOString()});return agent}
const failure=(code,details={})=>Object.assign(new Error(code),{code,details});
