import { createHash, randomUUID } from 'node:crypto';

const allowedTypes=new Set(['energy','drive','control','thermal','body']);
const cleanText=(value,max=120)=>String(value||'').trim().slice(0,max);
export function validateArchitecture({nodes,links}){
  if(!Array.isArray(nodes)||!nodes.length)throw failure('architecture_nodes_required');
  if(!Array.isArray(links))throw failure('architecture_links_required');
  const ids=new Set(),normalizedNodes=nodes.map(node=>{const id=cleanText(node.id,64);if(!id||ids.has(id))throw failure('architecture_node_id_invalid',{id});ids.add(id);const x=Number(node.x),y=Number(node.y);if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||x>100||y<0||y>100)throw failure('architecture_position_invalid',{id,x,y});if(!allowedTypes.has(node.type))throw failure('architecture_type_invalid',{id,type:node.type});return{id,x:Number(x.toFixed(2)),y:Number(y.toFixed(2)),title:cleanText(node.title),sub:cleanText(node.sub),type:node.type,interfaces:Array.isArray(node.interfaces)?[...new Set(node.interfaces.map(x=>cleanText(x,32)).filter(Boolean))]:[]}}),seen=new Set(),normalizedLinks=links.map(link=>{const from=cleanText(Array.isArray(link)?link[0]:link.from,64),to=cleanText(Array.isArray(link)?link[1]:link.to,64),key=`${from}->${to}`;if(!ids.has(from)||!ids.has(to)||from===to||seen.has(key))throw failure('architecture_link_invalid',{from,to});seen.add(key);return{from,to,interface:cleanText(Array.isArray(link)?'':link.interface,32)||'logical'}});
  const types=new Set(normalizedNodes.map(x=>x.type)),issues=[];for(const type of ['control','energy','drive'])if(!types.has(type))issues.push({severity:'critical',code:`missing_${type}_domain`});const connected=new Set(normalizedLinks.flatMap(x=>[x.from,x.to]));for(const node of normalizedNodes)if(!connected.has(node.id))issues.push({severity:'high',code:'orphan_component',nodeId:node.id});return{nodes:normalizedNodes,links:normalizedLinks,issues,valid:!issues.some(x=>x.severity==='critical')};
}
export function createArchitectureRevision(db,{projectId,name='EV Architecture',nodes,links,actor}){const validated=validateArchitecture({nodes,links}),previous=(db.architectures||[]).filter(x=>x.projectId===projectId).sort((a,b)=>b.revision-a.revision)[0],canonical=JSON.stringify({nodes:validated.nodes,links:validated.links}),revision={id:`ARCH-${randomUUID().slice(0,8)}`,projectId,name:cleanText(name),revision:(previous?.revision||0)+1,parentId:previous?.id||null,nodes:validated.nodes,links:validated.links,issues:validated.issues,valid:validated.valid,sha256:createHash('sha256').update(canonical).digest('hex'),createdBy:actor,createdAt:new Date().toISOString()};db.architectures??=[];db.architectures.unshift(revision);db.changes?.unshift({id:randomUUID(),projectId,type:'architecture.revised',target:revision.id,source:revision.parentId,at:revision.createdAt,actor});return revision}
const failure=(code,details={})=>Object.assign(new Error(code),{code,details});
