import test from 'node:test';
import assert from 'node:assert/strict';
import { authenticate, createUser, ensureIdentitySeed, hashPassword, login, logout, resetPassword, updateMembership, verifyPassword } from './auth.js';

test('password hashing verifies without storing plaintext',()=>{const stored=hashPassword('secret');assert.ok(!JSON.stringify(stored).includes('secret'));assert.equal(verifyPassword('secret',stored),true);assert.equal(verifyPassword('wrong',stored),false)});
test('session login, authentication and revocation lifecycle',()=>{const db={organizations:[],users:[],sessions:[]};ensureIdentitySeed(db);const result=login(db,'lead@autoforge.local','autoforge-demo');assert.ok(result.token);assert.equal(authenticate(db,result.token).user.id,'user-lead');assert.equal(logout(db,result.token),true);assert.equal(authenticate(db,result.token),null)});
test('invalid credentials reveal no user details',()=>{const db={organizations:[],users:[],sessions:[]};ensureIdentitySeed(db);assert.equal(login(db,'lead@autoforge.local','bad'),null);assert.equal(login(db,'missing@example.com','bad'),null)});
test('organization admin can create role members',()=>{const db={users:[],sessions:[]},user=createUser(db,{email:'safety@example.com',password:'long-password-123',organizationId:'o',role:'safety_officer'});assert.equal(user.memberships[0].role,'safety_officer');assert.throws(()=>createUser(db,{email:'safety@example.com',password:'long-password-123',organizationId:'o'}),e=>e.code==='email_exists')});
test('disabling user revokes sessions',()=>{const db={organizations:[],users:[],sessions:[]};ensureIdentitySeed(db);const result=login(db,'lead@autoforge.local','autoforge-demo');db.users.push({id:'other',active:true,memberships:[{organizationId:'org-autoforge',role:'admin'}]});updateMembership(db,{userId:'user-lead',organizationId:'org-autoforge',active:false});assert.equal(authenticate(db,result.token),null)});
test('last active organization admin is protected',()=>{const db={organizations:[],users:[],sessions:[]};ensureIdentitySeed(db);assert.throws(()=>updateMembership(db,{userId:'user-lead',organizationId:'org-autoforge',active:false}),e=>e.code==='last_admin_protected')});
test('password reset revokes sessions and accepts new password',()=>{const db={organizations:[],users:[],sessions:[]};ensureIdentitySeed(db);const before=login(db,'lead@autoforge.local','autoforge-demo');resetPassword(db,{userId:'user-lead',password:'new-strong-password'});assert.equal(authenticate(db,before.token),null);assert.ok(login(db,'lead@autoforge.local','new-strong-password'))});
