import crypto from 'node:crypto';
import { randomUUID } from 'node:crypto';

const ITERATIONS=120000,KEYLEN=32,DIGEST='sha256';
export function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.pbkdf2Sync(password,salt,ITERATIONS,KEYLEN,DIGEST).toString('hex');return{salt,hash,iterations:ITERATIONS,digest:DIGEST}}
export function verifyPassword(password,stored){const candidate=crypto.pbkdf2Sync(password,stored.salt,stored.iterations||ITERATIONS,KEYLEN,stored.digest||DIGEST);const expected=Buffer.from(stored.hash,'hex');return candidate.length===expected.length&&crypto.timingSafeEqual(candidate,expected)}
const tokenHash=token=>crypto.createHash('sha256').update(token).digest('hex');
export function ensureIdentitySeed(db){db.organizations??=[{id:'org-autoforge',name:'AutoForge Mobility Lab',slug:'autoforge'}];db.users??=[];db.sessions??=[];if(!db.users.length)db.users.push({id:'user-lead',email:'lead@autoforge.local',name:'정우 김',password:hashPassword(process.env.AUTOFORGE_DEMO_PASSWORD||'autoforge-demo'),memberships:[{organizationId:'org-autoforge',role:'admin'}],active:true,createdAt:new Date().toISOString()})}
export function login(db,email,password,{ttlHours=12}={}){const user=db.users.find(x=>x.email.toLowerCase()===String(email).toLowerCase()&&x.active);if(!user||!verifyPassword(password,user.password))return null;const token=crypto.randomBytes(32).toString('base64url'),session={id:randomUUID(),tokenHash:tokenHash(token),userId:user.id,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+ttlHours*3600000).toISOString(),lastSeenAt:new Date().toISOString()};db.sessions.push(session);return{token,session,user:safeUser(user)}}
export function authenticate(db,token){if(!token)return null;const session=db.sessions.find(x=>x.tokenHash===tokenHash(token)&&!x.revokedAt&&new Date(x.expiresAt)>new Date());if(!session)return null;const user=db.users.find(x=>x.id===session.userId&&x.active);if(!user)return null;session.lastSeenAt=new Date().toISOString();return{session,user:safeUser(user)}}
export function logout(db,token){const session=db.sessions.find(x=>x.tokenHash===tokenHash(token));if(!session)return false;session.revokedAt=new Date().toISOString();return true}
export const safeUser=user=>({id:user.id,email:user.email,name:user.name,memberships:user.memberships,active:user.active});
export function createUser(db,{email,name,password,organizationId,role='viewer'}){if(!/^\S+@\S+\.\S+$/.test(email||''))throw authError('invalid_email');if(String(password||'').length<12)throw authError('weak_password');if(db.users.some(x=>x.email.toLowerCase()===email.toLowerCase()))throw authError('email_exists');const user={id:randomUUID(),email:email.toLowerCase(),name:name||email,password:hashPassword(password),memberships:[{organizationId,role}],active:true,createdAt:new Date().toISOString()};db.users.push(user);return safeUser(user)}
export function updateMembership(db,{userId,organizationId,role,active}){const user=db.users.find(x=>x.id===userId);if(!user)throw authError('user_not_found');if(role){const membership=user.memberships.find(x=>x.organizationId===organizationId);if(membership)membership.role=role;else user.memberships.push({organizationId,role})}if(active!==undefined){if(active===false&&user.memberships.some(x=>x.organizationId===organizationId&&x.role==='admin')){const admins=db.users.filter(x=>x.active&&x.id!==user.id&&x.memberships.some(m=>m.organizationId===organizationId&&m.role==='admin'));if(!admins.length)throw authError('last_admin_protected')}user.active=Boolean(active);if(!user.active)for(const session of db.sessions.filter(x=>x.userId===user.id&&!x.revokedAt))session.revokedAt=new Date().toISOString()}user.updatedAt=new Date().toISOString();return safeUser(user)}
export function resetPassword(db,{userId,password}){if(String(password||'').length<12)throw authError('weak_password');const user=db.users.find(x=>x.id===userId);if(!user)throw authError('user_not_found');user.password=hashPassword(password);for(const session of db.sessions.filter(x=>x.userId===user.id&&!x.revokedAt))session.revokedAt=new Date().toISOString();user.updatedAt=new Date().toISOString();return true}
const authError=code=>Object.assign(new Error(code),{code});
