import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createBackup, restoreBackup, verifyBackup } from './backup.js';

test('backup verifies and restores database with artifacts',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'af-backup-test-'));try{const source=path.join(root,'source'),artifacts=path.join(source,'artifacts'),backup=path.join(root,'backup'),restore=path.join(root,'restore');fs.mkdirSync(artifacts,{recursive:true});fs.writeFileSync(path.join(source,'autoforge.json'),'{}');fs.writeFileSync(path.join(artifacts,'part.step'),'CAD');const manifest=createBackup({dataFile:path.join(source,'autoforge.json'),artifactDir:artifacts,destination:backup});assert.equal(manifest.files.length,2);assert.equal(verifyBackup(backup).valid,true);const result=restoreBackup({source:backup,dataDir:restore,artifactDir:path.join(restore,'artifacts')});assert.equal(result.restored,true);assert.equal(fs.readFileSync(path.join(restore,'artifacts','part.step'),'utf8'),'CAD')}finally{fs.rmSync(root,{recursive:true,force:true})}});
test('tampered backup is rejected',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'af-backup-test-'));try{const source=path.join(root,'source'),backup=path.join(root,'backup');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'autoforge.json'),'{}');createBackup({dataFile:path.join(source,'autoforge.json'),artifactDir:path.join(source,'none'),destination:backup});fs.writeFileSync(path.join(backup,'autoforge.json'),'tampered');const result=verifyBackup(backup);assert.equal(result.valid,false);assert.ok(result.errors.some(x=>x.startsWith('checksum:')))}finally{fs.rmSync(root,{recursive:true,force:true})}});
test('restore refuses non-empty target without force',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'af-backup-test-'));try{const source=path.join(root,'source'),backup=path.join(root,'backup'),target=path.join(root,'target');fs.mkdirSync(source);fs.mkdirSync(target);fs.writeFileSync(path.join(source,'autoforge.json'),'{}');fs.writeFileSync(path.join(target,'keep'),'x');createBackup({dataFile:path.join(source,'autoforge.json'),artifactDir:path.join(source,'none'),destination:backup});assert.throws(()=>restoreBackup({source:backup,dataDir:target,artifactDir:path.join(target,'artifacts')}),/not empty/)}finally{fs.rmSync(root,{recursive:true,force:true})}});
