import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const hashFile=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const listFiles=(root,base=root)=>fs.existsSync(root)?fs.readdirSync(root,{withFileTypes:true}).flatMap(e=>e.isDirectory()?listFiles(path.join(root,e.name),base):[{absolute:path.join(root,e.name),relative:path.relative(base,path.join(root,e.name))}]):[];
export function createBackup({dataFile,artifactDir,destination}){if(!fs.existsSync(dataFile))throw new Error('data file not found');if(fs.existsSync(destination))throw new Error('backup destination already exists');const temp=`${destination}.${process.pid}.tmp`;fs.mkdirSync(temp,{recursive:true});fs.copyFileSync(dataFile,path.join(temp,'autoforge.json'));if(fs.existsSync(artifactDir))fs.cpSync(artifactDir,path.join(temp,'artifacts'),{recursive:true});const files=listFiles(temp).filter(x=>x.relative!=='manifest.json').map(x=>({path:x.relative,size:fs.statSync(x.absolute).size,sha256:hashFile(x.absolute)}));const manifest={format:'autoforge-backup',version:1,createdAt:new Date().toISOString(),files};fs.writeFileSync(path.join(temp,'manifest.json'),JSON.stringify(manifest,null,2));fs.renameSync(temp,destination);return manifest}
export function verifyBackup(source){const manifestPath=path.join(source,'manifest.json');if(!fs.existsSync(manifestPath))return{valid:false,errors:['manifest_missing']};const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8')),errors=[];if(manifest.format!=='autoforge-backup')errors.push('format_invalid');for(const item of manifest.files||[]){const file=path.resolve(source,item.path);if(!file.startsWith(`${path.resolve(source)}${path.sep}`)){errors.push(`unsafe_path:${item.path}`);continue}if(!fs.existsSync(file)){errors.push(`missing:${item.path}`);continue}if(fs.statSync(file).size!==item.size)errors.push(`size:${item.path}`);if(hashFile(file)!==item.sha256)errors.push(`checksum:${item.path}`)}return{valid:errors.length===0,errors,manifest}}
export function restoreBackup({source,dataDir,artifactDir,force=false}){const verification=verifyBackup(source);if(!verification.valid)throw new Error(`backup verification failed: ${verification.errors.join(',')}`);if(fs.existsSync(dataDir)&&fs.readdirSync(dataDir).length&&!force)throw new Error('restore target is not empty');fs.mkdirSync(dataDir,{recursive:true});fs.copyFileSync(path.join(source,'autoforge.json'),path.join(dataDir,'autoforge.json'));const sourceArtifacts=path.join(source,'artifacts');if(fs.existsSync(sourceArtifacts)){if(fs.existsSync(artifactDir)&&force)fs.rmSync(artifactDir,{recursive:true,force:true});fs.mkdirSync(path.dirname(artifactDir),{recursive:true});fs.cpSync(sourceArtifacts,artifactDir,{recursive:true})}return{restored:true,files:verification.manifest.files.length}}
