import { randomUUID } from 'node:crypto';

export const changePolicies={documentation:{grade:'S0',autoApply:true},ui_copy:{grade:'S1',autoApply:true},test_only:{grade:'S1',autoApply:true},performance:{grade:'S2',autoApply:false},design_algorithm:{grade:'S2',autoApply:false},safety_rule:{grade:'S3',autoApply:false},robot_control:{grade:'S4',autoApply:false},deployment_policy:{grade:'S5',autoApply:false}};
const stages=['draft','reviewed','tested','benchmarked','security_verified','approval_pending','approved','canary','deployed'];
export function createImprovement({organizationId,title,description,type,artifactId,author,issueId=null}){const policy=changePolicies[type];if(!policy)throw pipelineError('invalid_change_type');if(!artifactId)throw pipelineError('patch_artifact_required');return{id:randomUUID(),organizationId,title,description,type,artifactId,issueId,author,riskGrade:policy.grade,autoApply:policy.autoApply,status:'draft',createdAt:new Date().toISOString(),history:[{state:'draft',actor:author,at:new Date().toISOString()}],evidence:{reviews:[],tests:null,benchmark:null,security:null},canary:null}}
export function advanceImprovement(run,{action,actor,role,evidence={},approval=null}){const expected={review:'draft',test:'reviewed',benchmark:'tested',security:'benchmarked',request_approval:'security_verified',approve:'approval_pending'}[action];if(expected&&run.status!==expected)throw pipelineError('invalid_pipeline_transition',{expected,actual:run.status});if(action==='review'){if(actor===run.author)throw pipelineError('independent_review_required');if(!['reviewer','admin'].includes(role))throw pipelineError('reviewer_role_required');if(evidence.decision!=='approved')return fail(run,'review_rejected',actor,evidence);run.evidence.reviews.push({actor,decision:'approved',comments:evidence.comments||'',at:new Date().toISOString()});transition(run,'reviewed',actor)}else if(action==='test'){if(!evidence.total||evidence.failed) return fail(run,'tests_failed',actor,evidence);run.evidence.tests={...evidence,at:new Date().toISOString()};transition(run,'tested',actor)}else if(action==='benchmark'){const result=compareBenchmark(evidence.baseline,evidence.candidate);run.evidence.benchmark={...result,baseline:evidence.baseline,candidate:evidence.candidate,at:new Date().toISOString()};if(!result.passed)return fail(run,'benchmark_regression',actor,result);transition(run,'benchmarked',actor)}else if(action==='security'){run.evidence.security={...evidence,at:new Date().toISOString()};if((evidence.critical||0)>0||(evidence.high||0)>0)return fail(run,'security_findings',actor,evidence);transition(run,'security_verified',actor)}else if(action==='request_approval'){transition(run,run.autoApply?'approved':'approval_pending',actor)}else if(action==='approve'){if(!approval||approval.status!=='approved'||approval.grade!==run.riskGrade)throw pipelineError('matching_approval_required');run.approvalId=approval.id;transition(run,'approved',actor)}else throw pipelineError('invalid_action');return run}
export function startCanary(run,{actor,percent=5,baseline}){if(run.status!=='approved')throw pipelineError('improvement_not_approved');if(percent<=0||percent>10)throw pipelineError('canary_percent_limit');run.canary={percent,baseline,observations:[],startedAt:new Date().toISOString(),status:'running'};transition(run,'canary',actor);return run}
export function observeCanary(run,{actor,metrics}){if(run.status!=='canary'||run.canary?.status!=='running')throw pipelineError('canary_not_running');run.canary.observations.push({metrics,at:new Date().toISOString()});const b=run.canary.baseline||{},regression=(metrics.errorRate??0)>(b.errorRate??0)+.02||(metrics.p95LatencyMs??0)>(b.p95LatencyMs??Infinity)*1.1||(metrics.successRate??1)<(b.successRate??1)-.02;if(regression){run.canary.status='regressed';run.rollback={reason:'canary_regression',metrics,at:new Date().toISOString()};transition(run,'rolled_back',actor);return run}if(run.canary.observations.length>=3){run.canary.status='passed';transition(run,'deployed',actor);run.deployedAt=new Date().toISOString()}return run}
export function rollbackImprovement(run,{actor,reason='manual_rollback'}){if(!['canary','deployed'].includes(run.status))throw pipelineError('rollback_not_available');run.rollback={reason,at:new Date().toISOString()};transition(run,'rolled_back',actor);return run}
export function compareBenchmark(baseline={},candidate={}){const latencyRatio=baseline.p95LatencyMs?candidate.p95LatencyMs/baseline.p95LatencyMs:1,successDelta=(candidate.successRate??1)-(baseline.successRate??1),costRatio=baseline.cost?candidate.cost/baseline.cost:1,passed=latencyRatio<=1.05&&successDelta>=-.005&&costRatio<=1.05;return{passed,latencyRatio:Number(latencyRatio.toFixed(4)),successDelta:Number(successDelta.toFixed(4)),costRatio:Number(costRatio.toFixed(4))}}
function transition(run,state,actor){run.status=state;run.updatedAt=new Date().toISOString();run.history.push({state,actor,at:run.updatedAt})}
function fail(run,reason,actor,evidence){run.failure={reason,evidence,at:new Date().toISOString()};transition(run,'failed',actor);return run}
const pipelineError=(code,details={})=>Object.assign(new Error(code),{code,details});
