import test from 'node:test';
import assert from 'node:assert/strict';
import { advanceImprovement, compareBenchmark, createImprovement, observeCanary, rollbackImprovement, startCanary } from './improvement.js';

const create=(type='performance')=>createImprovement({organizationId:'o',title:'Improve',type,artifactId:'artifact',author:'author'});
const passToApproval=run=>{advanceImprovement(run,{action:'review',actor:'reviewer',role:'reviewer',evidence:{decision:'approved'}});advanceImprovement(run,{action:'test',actor:'ci',role:'reviewer',evidence:{total:10,failed:0}});advanceImprovement(run,{action:'benchmark',actor:'ci',role:'reviewer',evidence:{baseline:{p95LatencyMs:100,successRate:.99,cost:10},candidate:{p95LatencyMs:95,successRate:.995,cost:10}}});advanceImprovement(run,{action:'security',actor:'security',role:'safety_officer',evidence:{critical:0,high:0}});advanceImprovement(run,{action:'request_approval',actor:'system',role:'reviewer'});return run};
test('author cannot review own platform change',()=>{const run=create();assert.throws(()=>advanceImprovement(run,{action:'review',actor:'author',role:'reviewer',evidence:{decision:'approved'}}),e=>e.code==='independent_review_required')});
test('benchmark regression fails pipeline',()=>{const run=create();advanceImprovement(run,{action:'review',actor:'r',role:'reviewer',evidence:{decision:'approved'}});advanceImprovement(run,{action:'test',actor:'ci',role:'reviewer',evidence:{total:2,failed:0}});advanceImprovement(run,{action:'benchmark',actor:'ci',role:'reviewer',evidence:{baseline:{p95LatencyMs:100,successRate:1},candidate:{p95LatencyMs:120,successRate:.9}}});assert.equal(run.status,'failed');assert.equal(run.failure.reason,'benchmark_regression')});
test('S2 improvement requires matching human approval',()=>{const run=passToApproval(create());assert.equal(run.status,'approval_pending');assert.throws(()=>advanceImprovement(run,{action:'approve',actor:'a',role:'reviewer',approval:{grade:'S1',status:'approved'}}),e=>e.code==='matching_approval_required');advanceImprovement(run,{action:'approve',actor:'a',role:'reviewer',approval:{id:'approval',grade:'S2',status:'approved'}});assert.equal(run.status,'approved')});
test('safe documentation change auto-approves after gates',()=>{const run=passToApproval(create('documentation'));assert.equal(run.status,'approved')});
test('canary regression triggers automatic rollback',()=>{const run=passToApproval(create('documentation'));startCanary(run,{actor:'ops',percent:5,baseline:{errorRate:.01,p95LatencyMs:100,successRate:.99}});observeCanary(run,{actor:'ops',metrics:{errorRate:.05,p95LatencyMs:100,successRate:.95}});assert.equal(run.status,'rolled_back');assert.equal(run.rollback.reason,'canary_regression')});
test('three healthy canary observations deploy release',()=>{const run=passToApproval(create('documentation'));startCanary(run,{actor:'ops',percent:5,baseline:{errorRate:.01,p95LatencyMs:100,successRate:.99}});for(let i=0;i<3;i++)observeCanary(run,{actor:'ops',metrics:{errorRate:.005,p95LatencyMs:95,successRate:.995}});assert.equal(run.status,'deployed');rollbackImprovement(run,{actor:'ops',reason:'manual'});assert.equal(run.status,'rolled_back')});
test('benchmark comparison enforces latency, success and cost guardrails',()=>{assert.equal(compareBenchmark({p95LatencyMs:100,successRate:1,cost:10},{p95LatencyMs:104,successRate:.999,cost:10.4}).passed,true);assert.equal(compareBenchmark({p95LatencyMs:100,successRate:1,cost:10},{p95LatencyMs:106,successRate:1,cost:10}).passed,false)});
