import { randomUUID } from 'node:crypto';

export class JobQueue {
  constructor({jobs=[],events=[],concurrency=2,clock=()=>new Date().toISOString(),onChange=()=>{}}={}){this.jobs=jobs;this.events=events;this.concurrency=concurrency;this.clock=clock;this.onChange=onChange;this.handlers=new Map();this.listeners=new Set();this.timer=null;for(const job of jobs)if(job.status==='running'){job.status='queued';job.recoveredAt=this.clock();}}
  register(type,handler){this.handlers.set(type,handler);return this;}
  enqueue({type,payload={},dependsOn=[],maxAttempts=3,priority=0,runId=null,safetyGrade='S0'}){const job={id:randomUUID(),type,payload,dependsOn,maxAttempts,priority,runId,safetyGrade,status:'queued',attempts:0,createdAt:this.clock(),result:null,error:null};this.jobs.push(job);this.emit(job,'job.queued');return job;}
  emit(job,type,data={}){const event={id:randomUUID(),jobId:job.id,runId:job.runId,type,at:this.clock(),...data};this.events.unshift(event);if(this.events.length>5000)this.events.length=5000;this.onChange({job,event});for(const listener of this.listeners)listener(event);return event;}
  subscribe(listener){this.listeners.add(listener);return()=>this.listeners.delete(listener)}
  ready(job){return job.status==='queued'&&job.dependsOn.every(id=>this.jobs.find(x=>x.id===id)?.status==='complete');}
  async tick(){for(const job of this.jobs.filter(j=>j.status==='queued')){const failedDependency=job.dependsOn.map(id=>this.jobs.find(x=>x.id===id)).find(x=>x&&['failed','blocked','cancelled'].includes(x.status));if(failedDependency){job.status='blocked';job.error={type:'dependency_failure',message:`Dependency ${failedDependency.id} is ${failedDependency.status}`,retryable:false};this.emit(job,'job.blocked',{error:job.error})}}const active=this.jobs.filter(j=>j.status==='running').length;const slots=Math.max(0,this.concurrency-active);const ready=this.jobs.filter(j=>this.ready(j)).sort((a,b)=>b.priority-a.priority||a.createdAt.localeCompare(b.createdAt)).slice(0,slots);await Promise.all(ready.map(j=>this.execute(j)));return ready.length;}
  async execute(job){const handler=this.handlers.get(job.type);if(!handler){job.status='failed';job.error={type:'platform_failure',message:`No handler: ${job.type}`};this.emit(job,'job.failed',{error:job.error});return job}job.status='running';job.attempts++;job.startedAt=this.clock();this.emit(job,'job.started',{attempt:job.attempts});try{job.result=await handler(job.payload,{job,queue:this});job.status='complete';job.completedAt=this.clock();this.emit(job,'job.completed',{result:job.result})}catch(error){job.error={type:error.type||'platform_failure',message:error.message,retryable:error.retryable!==false,...(error.details===undefined?{}:{details:error.details})};if(job.error.retryable&&job.attempts<job.maxAttempts){job.status='queued';this.emit(job,'job.retry_scheduled',{error:job.error,attempt:job.attempts})}else{job.status=error.type==='safety_failure'?'blocked':'failed';job.completedAt=this.clock();this.emit(job,job.status==='blocked'?'job.blocked':'job.failed',{error:job.error})}}return job;}
  retry(id){const job=this.jobs.find(j=>j.id===id);if(!job||!['failed','blocked'].includes(job.status))return null;job.status='queued';job.error=null;this.emit(job,'job.manual_retry');return job;}
  cancel(id,actor='system'){const job=this.jobs.find(j=>j.id===id);if(!job||['complete','cancelled'].includes(job.status))return null;job.status='cancelled';job.completedAt=this.clock();this.emit(job,'job.cancelled',{actor});return job;}
  start(interval=150){if(this.timer)return;this.timer=setInterval(()=>this.tick().catch(()=>{}),interval);this.timer.unref?.()}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
}
