import test from 'node:test';
import assert from 'node:assert/strict';
import { buildKnowledgeGraph, impactAnalysis, traceabilityScore } from './knowledgeGraph.js';

const db={projects:[{id:'p',name:'P'}],requirements:[{id:'r',projectId:'p',title:'Range'}],goals:[],designs:[{id:'d',projectId:'p',name:'D'}],simulations:[{id:'s',projectId:'p',designId:'d',name:'Sim'}],evidence:[{id:'e',sourceId:'s',claim:'pass'}],changes:[],approvals:[],knowledge:[]};
test('graph connects requirement, design, simulation and evidence',()=>{const g=buildKnowledgeGraph(db,'p');assert.equal(g.stats.traceability,1);assert.ok(g.edges.some(x=>x.type==='verified_by'));assert.ok(g.edges.some(x=>x.type==='produces'))});
test('impact analysis traverses connected evidence',()=>{const result=impactAnalysis(buildKnowledgeGraph(db,'p'),'r');assert.ok(result.impacts.some(x=>x.id==='s'));assert.ok(result.count>=2)});
test('empty requirements report zero traceability',()=>assert.equal(traceabilityScore([],[]),0));
test('active baseline traceability requires a passing verification linked to existing evidence',()=>{const scoped={...db,requirements:[{id:'r',projectId:'p',title:'Range',status:'pass',baselineId:'b'}],requirementBaselines:[{id:'b',projectId:'p',status:'active',requirementIds:['r']}],requirementVerifications:[],engineExecutions:[],manufacturingEvaluations:[],physicalTests:[]};assert.equal(buildKnowledgeGraph(scoped,'p').stats.traceability,0);scoped.requirementVerifications.push({id:'v',projectId:'p',requirementId:'r',status:'pass',evidenceId:'s',evidenceType:'simulation.range'});const graph=buildKnowledgeGraph(scoped,'p');assert.equal(graph.stats.traceability,1);assert.ok(graph.edges.some(x=>x.from==='r'&&x.to==='v'&&x.type==='verified_by_evidence'));assert.ok(graph.edges.some(x=>x.from==='v'&&x.to==='s'&&x.type==='supported_by'))});
test('orphan verification evidence cannot produce traceability',()=>{const scoped={...db,requirements:[{id:'r',projectId:'p',title:'Range',status:'pass'}],requirementBaselines:[{id:'b',projectId:'p',status:'active',requirementIds:['r']}],requirementVerifications:[{id:'v',projectId:'p',requirementId:'r',status:'pass',evidenceId:'missing'}],engineExecutions:[],manufacturingEvaluations:[],physicalTests:[]};assert.equal(buildKnowledgeGraph(scoped,'p').stats.traceability,0)});
test('architecture revisions expose component interfaces and parent lineage',()=>{const scoped={...db,architectures:[{id:'a1',projectId:'p',name:'EV',revision:1,nodes:[{id:'vcu',title:'VCU'},{id:'bat',title:'Pack'}],links:[{from:'vcu',to:'bat',interface:'CAN'}]},{id:'a2',parentId:'a1',projectId:'p',name:'EV',revision:2,nodes:[],links:[]}]},graph=buildKnowledgeGraph(scoped,'p');assert.ok(graph.edges.some(x=>x.from==='a1'&&x.to==='a2'&&x.type==='derived_into'));assert.ok(graph.edges.some(x=>x.from==='a1:vcu'&&x.to==='a1:bat'&&x.type==='interfaces_with'));assert.ok(graph.nodes.some(x=>x.id==='a1:vcu'&&x.type==='component'))});
