import { randomUUID } from 'node:crypto';

export function evaluateManufacturing({projectId='urban-e04',designId,bom=[],suppliers=[],parameters={},targetCost=30000000}){
  const issues=[],partResults=[];let directCost=0,assemblySeconds=0;
  for(const part of bom){const extended=(Number(part.unitCost)||0)*(Number(part.qty)||0);directCost+=extended;assemblySeconds+=estimateAssembly(part);const sources=(part.supplierIds||[]).map(id=>suppliers.find(s=>s.id===id)).filter(Boolean),risks=[];if(!sources.length)risks.push('no_supplier');if(sources.length===1)risks.push('single_source');if(sources.some(s=>s.risk==='high'))risks.push('high_risk_supplier');if(sources.some(s=>s.leadTimeDays>90))risks.push('long_lead_time');if(part.status==='risk')risks.push('part_risk');partResults.push({partNo:part.partNo,extendedCost:extended,supplierCount:sources.length,risks});for(const risk of risks)issues.push({type:'supply',severity:risk==='no_supplier'?'critical':risk.includes('high_risk')?'high':'medium',partNo:part.partNo,code:risk})}
  if((parameters.length||0)>4000)issues.push({type:'dfm',severity:'critical',code:'vehicle_length_limit',actual:parameters.length,limit:4000});if(parameters.minWallThickness!=null&&parameters.minWallThickness<1.2)issues.push({type:'dfm',severity:'high',code:'wall_thickness',actual:parameters.minWallThickness,limit:1.2});if(parameters.uniqueFasteners>12)issues.push({type:'assembly',severity:'medium',code:'fastener_variety',actual:parameters.uniqueFasteners,limit:12});
  const overhead=directCost*.18,labor=assemblySeconds/3600*42000,totalCost=Math.round(directCost+overhead+labor),critical=issues.some(x=>x.severity==='critical'),costPassed=totalCost<=targetCost;
  return{id:randomUUID(),projectId,designId,createdAt:new Date().toISOString(),cost:{direct:directCost,overhead:Math.round(overhead),labor:Math.round(labor),total:totalCost,target:targetCost,passed:costPassed},assembly:{seconds:assemblySeconds,stations:Math.max(1,Math.ceil(assemblySeconds/480)),complexity:assemblySeconds>3600?'high':assemblySeconds>1800?'medium':'low'},parts:partResults,issues,manufacturable:!critical&&costPassed,supplyRiskScore:riskScore(issues)};
}
const estimateAssembly=part=>{const base={Energy:420,Drive:260,Body:95,Thermal:180,'E/E':120}[part.system]||80;return base*(Number(part.qty)||1)};
const riskScore=issues=>Math.min(100,issues.reduce((n,x)=>n+({critical:40,high:22,medium:9,low:3}[x.severity]||0),0));
export function suggestAlternatives(evaluation,bom,suppliers){return evaluation.parts.filter(x=>x.risks.length).map(p=>{const part=bom.find(x=>x.partNo===p.partNo),alternatives=suppliers.filter(s=>!(part.supplierIds||[]).includes(s.id)&&s.risk!=='high'&&s.leadTimeDays<90).slice(0,3);return{partNo:p.partNo,currentRisks:p.risks,alternatives:alternatives.map(s=>({supplierId:s.id,name:s.name,risk:s.risk,leadTimeDays:s.leadTimeDays}))}})}
