import test from 'node:test';
import assert from 'node:assert/strict';
import { McpGateway, MCP_PROTOCOL_VERSION, validateMcpOrigin } from './mcpGateway.js';

const admin={id:'admin',organizationId:'org-a',role:'admin',authenticated:true};
const viewer={id:'viewer',organizationId:'org-a',role:'viewer',authenticated:true};
const initialize=async(gateway,actor=admin)=>{const response=await gateway.handle({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:MCP_PROTOCOL_VERSION,capabilities:{},clientInfo:{name:'test',version:'1'}}},{actor});const sessionId=response.sessionId;await gateway.handle({jsonrpc:'2.0',method:'notifications/initialized'},{actor,sessionId});return sessionId};

test('MCP initialization negotiates current version and tool capability',async()=>{const gateway=new McpGateway({execute:async()=>({})}),response=await gateway.handle({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:MCP_PROTOCOL_VERSION,clientInfo:{name:'test'}}},{actor:admin});assert.equal(response.result.protocolVersion,MCP_PROTOCOL_VERSION);assert.equal(response.result.capabilities.tools.listChanged,false);assert.ok(response.sessionId)});
test('MCP session is bound to actor and must receive initialized notification',async()=>{const gateway=new McpGateway({execute:async()=>({})}),init=await gateway.handle({jsonrpc:'2.0',id:1,method:'initialize',params:{}},{actor:admin});const early=await gateway.handle({jsonrpc:'2.0',id:2,method:'tools/list'},{actor:admin,sessionId:init.sessionId});assert.equal(early.error.code,-32002);const stolen=await gateway.handle({jsonrpc:'2.0',id:3,method:'tools/list'},{actor:viewer,sessionId:init.sessionId});assert.equal(stolen.error.code,-32001)});
test('tool list is filtered by RBAC and exposes safety annotations',async()=>{const gateway=new McpGateway({execute:async()=>({})}),sessionId=await initialize(gateway,viewer),response=await gateway.handle({jsonrpc:'2.0',id:2,method:'tools/list'},{actor:viewer,sessionId});assert.ok(response.result.tools.some(x=>x.name==='autoforge_project_list'));assert.ok(!response.result.tools.some(x=>x.name==='autoforge_robot_command'));const adminSession=await initialize(gateway,admin),adminList=await gateway.handle({jsonrpc:'2.0',id:3,method:'tools/list'},{actor:admin,sessionId:adminSession});assert.equal(adminList.result.tools.find(x=>x.name==='autoforge_robot_command').annotations.destructiveHint,true)});
test('tool call validates arguments and returns structured content',async()=>{const calls=[],gateway=new McpGateway({execute:async(name,args)=>{calls.push({name,args});return{range:420}}}),sessionId=await initialize(gateway),bad=await gateway.handle({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'autoforge_requirement_refine',arguments:{projectId:'p'}}},{actor:admin,sessionId});assert.equal(bad.error.code,-32602);const good=await gateway.handle({jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'autoforge_design_estimate',arguments:{length:3990}}},{actor:admin,sessionId});assert.equal(good.result.structuredContent.range,420);assert.equal(calls[0].name,'autoforge_design_estimate')});
test('domain execution errors are tool results so agents can self-correct',async()=>{const error=Object.assign(new Error('S4 approval required'),{code:'s4_approval_required'}),gateway=new McpGateway({execute:async()=>{throw error}}),sessionId=await initialize(gateway),response=await gateway.handle({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'autoforge_robot_command',arguments:{projectId:'p',cellId:'c',action:'robot.test',approvalId:'a',idempotencyKey:'k'}}},{actor:admin,sessionId});assert.equal(response.result.isError,true);assert.equal(response.result.structuredContent.error,'s4_approval_required')});
test('MCP origin validation accepts same host or allowlist only',()=>{assert.equal(validateMcpOrigin(undefined,{host:'localhost:4174'}),true);assert.equal(validateMcpOrigin('http://localhost:4174',{host:'localhost:4174'}),true);assert.equal(validateMcpOrigin('https://agent.example',{host:'localhost:4174',allowedOrigins:['https://agent.example']}),true);assert.equal(validateMcpOrigin('https://evil.example',{host:'localhost:4174'}),false)});
