import test from 'node:test';
import assert from 'node:assert/strict';
import { dominates, optimizeDesign, paretoFront, promoteCandidate } from './optimization.js';

const parent={id:'D-1',projectId:'P-1',version:'0.8',iteration:8,parameters:{length:3990,wheelbase:2630,height:1570,wheel:19,capacity:78.4}};
test('optimizer is reproducible and applies every hard constraint',()=>{const a=optimizeDesign({projectId:'P-1',parentDesign:parent,sampleSize:120,seed:42}),b=optimizeDesign({projectId:'P-1',parentDesign:parent,sampleSize:120,seed:42});assert.deepEqual(a.candidates.map(x=>x.parameters),b.candidates.map(x=>x.parameters));assert.equal(a.candidateCount,120);assert.ok(a.feasibleCount>0);for(const c of a.candidates.filter(x=>x.feasible)){assert.ok(c.parameters.length<=4000);assert.ok(c.metrics.range>=400);assert.ok(c.metrics.cost<=30);assert.ok(c.metrics.weight<=1900);assert.ok(c.metrics.cd<=.25)}});
test('Pareto front contains no candidate dominated by another feasible candidate',()=>{const run=optimizeDesign({projectId:'P-1',parentDesign:parent,sampleSize:250,seed:7}),front=run.candidates.filter(x=>x.pareto),feasible=run.candidates.filter(x=>x.feasible);assert.equal(front.length,run.paretoCount);assert.ok(front.length>1);for(const candidate of front)assert.equal(feasible.some(other=>other.id!==candidate.id&&dominates(other,candidate)),false);assert.deepEqual(paretoFront(feasible).map(x=>x.id).sort(),front.map(x=>x.id).sort())});
test('weights are normalized and recommendation belongs to Pareto set',()=>{const run=optimizeDesign({projectId:'P-1',parentDesign:parent,weights:{range:70,cost:20,weight:10,space:0}}),sum=Object.values(run.weights).reduce((a,b)=>a+b,0);assert.ok(Math.abs(sum-1)<.001);assert.ok(run.paretoCandidateIds.includes(run.recommendedCandidateId))});
test('promoted design preserves optimization lineage',()=>{const db={designs:[parent]},run=optimizeDesign({projectId:'P-1',parentDesign:parent,sampleSize:80}),design=promoteCandidate(db,run,run.recommendedCandidateId,{actor:'engineer'});assert.equal(design.parentDesignId,parent.id);assert.equal(design.optimizationRunId,run.id);assert.equal(design.lineage.seed,run.seed);assert.equal(run.promotions[0].designId,design.id)});
test('infeasible candidate cannot be promoted',()=>{const db={designs:[parent]},run=optimizeDesign({projectId:'P-1',parentDesign:parent,sampleSize:80}),candidate=run.candidates.find(x=>!x.feasible);assert.ok(candidate);assert.throws(()=>promoteCandidate(db,run,candidate.id),error=>error.code==='candidate_infeasible')});
