import { randomUUID } from 'node:crypto';
import { estimateVehicle } from './engines.js';

const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const halton=(index,base)=>{let fraction=1,result=0,i=index;while(i>0){fraction/=base;result+=fraction*(i%base);i=Math.floor(i/base)}return result};
const scale=(value,min,max)=>min+value*(max-min);
const constraints=[['length',value=>value<=4000,'전장 ≤ 4,000 mm'],['range',value=>value>=400,'주행거리 ≥ 400 km'],['cost',value=>value<=30,'제조원가 ≤ 30M KRW'],['weight',value=>value<=1900,'차량중량 ≤ 1,900 kg'],['cd',value=>value<=.25,'Cd ≤ 0.250']];

export function dominates(a,b){const noWorse=a.metrics.range>=b.metrics.range&&a.metrics.cost<=b.metrics.cost&&a.metrics.weight<=b.metrics.weight&&a.metrics.cd<=b.metrics.cd,strict=a.metrics.range>b.metrics.range||a.metrics.cost<b.metrics.cost||a.metrics.weight<b.metrics.weight||a.metrics.cd<b.metrics.cd;return noWorse&&strict}
export function paretoFront(candidates){return candidates.filter((candidate,index)=>!candidates.some((other,i)=>i!==index&&dominates(other,candidate)))}

export function optimizeDesign({projectId,parentDesign,sampleSize=250,seed=1,weights={range:.35,cost:.3,weight:.2,space:.15}}){
  const count=clamp(Math.round(sampleSize),20,1000),candidates=[];for(let i=1;i<=count;i++){const n=i+Math.abs(Math.round(seed))*997,parameters={length:Math.round(scale(halton(n,2),3800,4000)),wheelbase:Math.round(scale(halton(n,3),2500,2780)),height:Math.round(scale(halton(n,5),1450,1650)),width:Math.round(scale(halton(n,7),1750,1900)),wheel:Math.round(scale(halton(n,11),17,21)),capacity:Number(scale(halton(n,13),68,88).toFixed(1))};parameters.wheelbase=Math.min(parameters.wheelbase,parameters.length-650);const metrics=estimateVehicle(parameters),values={...parameters,...metrics},violations=constraints.filter(([key,test])=>!test(values[key])).map(([key,,label])=>({key,label,actual:values[key]}));candidates.push({id:`OPT-C${String(i).padStart(4,'0')}`,parentDesignId:parentDesign.id,parameters,metrics,feasible:violations.length===0,violations})}
  const feasible=candidates.filter(x=>x.feasible),front=paretoFront(feasible),scoringSet=feasible.length?feasible:candidates,ranges={range:extent(scoringSet,'range'),cost:extent(scoringSet,'cost'),weight:extent(scoringSet,'weight'),space:extentParameters(scoringSet,'wheelbase')},normalizedWeights=normalizeWeights(weights);for(const c of candidates){const utility=norm(c.metrics.range,ranges.range)*normalizedWeights.range+(1-norm(c.metrics.cost,ranges.cost))*normalizedWeights.cost+(1-norm(c.metrics.weight,ranges.weight))*normalizedWeights.weight+norm(c.parameters.wheelbase,ranges.space)*normalizedWeights.space;c.score=Math.round(utility*1000)/10;c.pareto=front.includes(c);c.philosophy=philosophy(c,scoringSet)}front.sort((a,b)=>b.score-a.score);return{id:randomUUID(),projectId,parentDesignId:parentDesign.id,algorithm:'halton-pareto-rom-1.0',seed,sampleSize:count,weights:normalizedWeights,constraints:constraints.map(([key,,label])=>({key,label,hard:true})),status:'complete',candidateCount:candidates.length,feasibleCount:feasible.length,paretoCount:front.length,candidates,paretoCandidateIds:front.map(x=>x.id),recommendedCandidateId:front[0]?.id||null,createdAt:new Date().toISOString()}}

export function promoteCandidate(db,run,candidateId,{actor='system'}={}){const candidate=run.candidates.find(x=>x.id===candidateId);if(!candidate)throw failure('candidate_not_found');if(!candidate.feasible)throw failure('candidate_infeasible');const parent=db.designs.find(x=>x.id===run.parentDesignId),design={id:`AF-O${randomUUID().slice(0,8).toUpperCase()}`,projectId:run.projectId,version:nextVersion(parent?.version),name:`Optimized ${candidate.philosophy}`,iteration:(parent?.iteration||0)+1,parentDesignId:run.parentDesignId,optimizationRunId:run.id,optimizationCandidateId:candidate.id,parameters:candidate.parameters,metrics:candidate.metrics,score:candidate.score,status:'candidate',createdAt:new Date().toISOString(),createdBy:actor,lineage:{method:run.algorithm,seed:run.seed,parentDesignId:run.parentDesignId}};db.designs.push(design);run.promotions??=[];run.promotions.push({candidateId,designId:design.id,actor,at:design.createdAt});return design}

const extent=(items,key)=>{const values=items.map(x=>x.metrics[key]);return[Math.min(...values),Math.max(...values)]};
const extentParameters=(items,key)=>{const values=items.map(x=>x.parameters[key]);return[Math.min(...values),Math.max(...values)]};
const norm=(value,[min,max])=>max===min?.5:(value-min)/(max-min);
const normalizeWeights=input=>{const values={range:Math.max(0,Number(input.range)||0),cost:Math.max(0,Number(input.cost)||0),weight:Math.max(0,Number(input.weight)||0),space:Math.max(0,Number(input.space)||0)},sum=Object.values(values).reduce((a,b)=>a+b,0)||1;return Object.fromEntries(Object.entries(values).map(([k,v])=>[k,Number((v/sum).toFixed(4))]))};
const philosophy=(candidate,all)=>{const best={range:Math.max(...all.map(x=>x.metrics.range)),cost:Math.min(...all.map(x=>x.metrics.cost)),weight:Math.min(...all.map(x=>x.metrics.weight)),space:Math.max(...all.map(x=>x.parameters.wheelbase))},distance={performance:best.range-candidate.metrics.range,cost:(candidate.metrics.cost-best.cost)*10,lightweight:(candidate.metrics.weight-best.weight)/10,space:(best.space-candidate.parameters.wheelbase)/5};return Object.entries(distance).sort((a,b)=>a[1]-b[1])[0][0]};
const nextVersion=version=>{const [major='0',minor='0']=String(version||'0.1').split('.');return`${major}.${Number(minor)+1}`};
const failure=code=>Object.assign(new Error(code),{code});
