import { randomUUID } from 'node:crypto';
import { estimateVehicle } from './engines.js';
import { activeRequirements, createRequirementDrafts } from './requirementLifecycle.js';

const workflowError=(message,type='platform_failure',retryable=false,details)=>Object.assign(new Error(message),{type,retryable,details});
const runJob=(queue,runId,type)=>queue.jobs.find(x=>x.runId===runId&&x.type===type);
const runDesign=(queue,job)=>queue.jobs.find(x=>x.runId===job.runId&&x.type==='design.generate'&&x.payload.iteration===job.payload.iteration)?.result;

export function registerWorkflowHandlers(queue,adapters,db,services={}){
  queue.register('requirements.refine',async payload=>{
    const baseline=(db.requirementBaselines||[]).find(x=>x.projectId===payload.projectId&&x.status==='active'),requirements=activeRequirements(db,payload.projectId);
    if(!baseline){
      const existingDrafts=db.requirements.filter(x=>x.projectId===payload.projectId&&x.lifecycleStatus==='draft');
      const batch=existingDrafts.length?{drafts:existingDrafts}:createRequirementDrafts(db,{projectId:payload.projectId,text:payload.prompt,actor:payload.actor||'orchestrator'});
      throw workflowError('요구사항 기준선의 인간 승인이 필요합니다','safety_failure',false,{draftIds:batch.drafts.map(x=>x.id),gate:'requirement_baseline'});
    }
    if(!requirements.length)throw workflowError('활성 요구사항 기준선이 비어 있습니다');
    return{baselineId:baseline.id,baselineVersion:baseline.version,requirementIds:requirements.map(x=>x.id)};
  })
  .register('design.generate',async payload=>{const metrics=estimateVehicle(payload.parameters||{}),design={id:`AF-GEN-${randomUUID().slice(0,6)}`,projectId:payload.projectId,name:`${payload.philosophy} · Iteration ${payload.iteration}`,iteration:payload.iteration,parentDesignId:payload.parentDesignId,parameters:payload.parameters||{},metrics,status:'generated',createdAt:new Date().toISOString(),createdBy:payload.actor||'orchestrator'};db.designs.push(design);return design})
  .register('cad.generate',async(payload,{job,queue:owner})=>{const design=runDesign(owner,job);if(!design)throw workflowError('workflow design result missing');return services.generateCad?services.generateCad(design,payload):adapters.execute('cad.parametric','package.generate',{...payload,designId:design.id})})
  .register('rules.check',async(payload,{job,queue:owner})=>{const design=runDesign(owner,job);return adapters.execute('manufacturing.rules','manufacturing.check',{...payload,designId:design.id,metrics:design.metrics})})
  .register('simulation.aero',(payload,context)=>executeSimulation('aero',payload,context,services,adapters))
  .register('simulation.thermal',(payload,context)=>executeSimulation('thermal',payload,context,services,adapters))
  .register('simulation.structure',(payload,context)=>executeSimulation('structure',payload,context,services,adapters))
  .register('simulation.range',(payload,context)=>executeSimulation('range',payload,context,services,adapters))
  .register('manufacturing.check',async(payload,{job,queue:owner})=>{const design=runDesign(owner,job);if(services.evaluateManufacturing)return services.evaluateManufacturing(design,payload);return adapters.execute('manufacturing.rules','manufacturing.check',{...payload,designId:design.id,metrics:design.metrics})})
  .register('validation.score',async(payload,{job,queue:owner})=>{const design=runDesign(owner,job),iteration=payload.iteration,simulations=['aero','thermal','structure','range'].map(type=>owner.jobs.find(x=>x.runId===job.runId&&x.type===`simulation.${type}`&&x.payload.iteration===iteration)?.result),manufacturing=owner.jobs.find(x=>x.runId===job.runId&&x.type==='manufacturing.check'&&x.payload.iteration===iteration)?.result,cad=owner.jobs.find(x=>x.runId===job.runId&&x.type==='cad.generate'&&x.payload.iteration===iteration)?.result,requirementVerification=services.verifyRequirements?await services.verifyRequirements(design,{cad,simulations,manufacturing},payload):{allPassed:true,verificationIds:[],failedCategories:[]},checks={simulations:simulations.every(Boolean),manufacturing:Boolean(manufacturing?.manufacturable),requirements:requirementVerification.allPassed,range:Number(design.metrics.range)>=400,cost:Number(design.metrics.cost)<=30,length:Number(design.parameters.length||3990)<=4000};const passed=Object.values(checks).every(Boolean);design.status=passed?'virtually_validated':'improvement_required';design.validation={checks,simulationIds:simulations.map(x=>x.simulation?.id||x.runId).filter(Boolean),manufacturingId:manufacturing?.id,requirementVerificationIds:requirementVerification.verificationIds,completedAt:new Date().toISOString()};if(!passed&&iteration<payload.maxIterations){const run=db.runs.find(x=>x.id===job.runId),parameters=improveParameters(design.parameters,checks,requirementVerification.failedCategories);enqueueEngineeringIteration(owner,run,{...payload,parameters,parentDesignId:design.id,iteration:iteration+1},job.id);return{designId:design.id,status:'improving',checks,nextIteration:iteration+1,parameters}}if(!passed)design.status='stagnated';return{designId:design.id,status:design.status,checks,iteration}});
}

async function executeSimulation(type,payload,{job,queue},services,adapters){const design=runDesign(queue,job);if(!design)throw workflowError('workflow design result missing');return services.runSimulation?services.runSimulation(design,type,payload):adapters.execute('simulation.multiphysics',`simulation.${type}`,{...payload,designId:design.id,metrics:design.metrics})}

export function startDesignWorkflow(queue,db,{projectId='urban-e04',prompt='',parameters={length:3990,wheelbase:2630,height:1570,wheel:19},actor='orchestrator',organizationId,parentRunId=null,resumeReason=null}={}){
  const run={id:randomUUID(),projectId,prompt,parameters,status:'running',progress:0,stage:'requirements.refine',startedAt:new Date().toISOString(),events:[],createdBy:actor,organizationId,parentRunId,resumeReason};db.runs.unshift(run);
  const payload={projectId,prompt,parameters,actor,organizationId,iteration:1,maxIterations:3,philosophy:'Balanced'},req=queue.enqueue({type:'requirements.refine',payload,runId:run.id,priority:10});run.jobIds=[req.id];enqueueEngineeringIteration(queue,run,payload,req.id);return run;
}

export function resumeDesignWorkflow(queue,db,runId,{parameters,actor='orchestrator',organizationId,reason='human_review'}={}){const source=db.runs.find(x=>x.id===runId);if(!source)throw workflowError('run_not_found');if(!['blocked','failed','needs_review'].includes(source.status))throw workflowError('run_not_resumable');if(source.resumedByRunId)throw workflowError('run_already_resumed');const resumed=startDesignWorkflow(queue,db,{projectId:source.projectId,prompt:source.prompt,parameters:parameters||source.parameters,actor,organizationId,parentRunId:source.id,resumeReason:reason});source.resumedByRunId=resumed.id;source.resumedAt=new Date().toISOString();source.resumedBy=actor;return resumed}

function enqueueEngineeringIteration(queue,run,payload,dependencyId){const design=queue.enqueue({type:'design.generate',payload,dependsOn:[dependencyId],runId:run.id,priority:8}),cad=queue.enqueue({type:'cad.generate',payload,dependsOn:[design.id],runId:run.id}),rules=queue.enqueue({type:'rules.check',payload,dependsOn:[cad.id],runId:run.id}),simulations=['aero','thermal','structure','range'].map(type=>queue.enqueue({type:`simulation.${type}`,payload,dependsOn:[rules.id],runId:run.id})),manufacturing=queue.enqueue({type:'manufacturing.check',payload,dependsOn:simulations.map(x=>x.id),runId:run.id}),score=queue.enqueue({type:'validation.score',payload,dependsOn:[manufacturing.id],runId:run.id});run.jobIds.push(design.id,cad.id,rules.id,...simulations.map(x=>x.id),manufacturing.id,score.id);run.iteration=payload.iteration;run.maxIterations=payload.maxIterations;return score}
function improveParameters(parameters,checks,failedCategories=[]){const next={...parameters},failed=new Set(failedCategories||[]);if(!checks.length||failed.has('dimension'))next.length=Math.min(4000,Number(next.length||3990));if(!checks.range||failed.has('performance')){next.capacity=Math.min(100,Number(next.capacity||78.4)+8);next.wheel=Math.min(19,Number(next.wheel||19))}if(!checks.cost||failed.has('cost'))next.capacity=Math.max(70,Number(next.capacity||78.4)-3);if(failed.has('aero')){next.height=Math.max(1450,Number(next.height||1570)-30);next.wheel=Math.max(17,Number(next.wheel||19)-1)}return next}

export function syncRun(run,jobs){const own=jobs.filter(j=>run.jobIds?.includes(j.id));if(!own.length)return run;const completed=own.filter(j=>j.status==='complete').length;run.progress=Math.round(completed/own.length*100);const blocked=own.find(j=>j.status==='blocked'),failed=own.find(j=>j.status==='failed'),stagnated=own.find(j=>j.type==='validation.score'&&j.result?.status==='stagnated');run.status=blocked?'blocked':failed?'failed':stagnated?'needs_review':completed===own.length?'complete':'running';run.stage=run.status==='needs_review'?'expert_handoff':own.find(j=>!['complete','cancelled'].includes(j.status))?.type||'complete';run.blocker=blocked?.error?.message||failed?.error?.message||(stagnated?'최대 반복 횟수 안에 설계 목표를 충족하지 못했습니다':undefined);run.gate=blocked?.error?.details?.gate||failed?.error?.type||(stagnated?'optimization_stagnation':undefined);run.failedJobId=failed?.id;if(['complete','needs_review','failed','blocked'].includes(run.status)&&!run.completedAt)run.completedAt=new Date().toISOString();return run}
