import test from 'node:test';
import assert from 'node:assert/strict';
import { JobQueue } from './jobs.js';
import { AdapterRegistry } from './adapters.js';
import { registerWorkflowHandlers, resumeDesignWorkflow, startDesignWorkflow, syncRun } from './orchestrator.js';

const executeAll=async queue=>{for(let i=0;i<20;i++){await queue.tick();if(queue.jobs.every(x=>['complete','failed','blocked','cancelled'].includes(x.status)))break}};
const approvedDb=()=>({requirements:[{id:'REQ-1',logicalId:'REQ-1',projectId:'p',title:'Range',status:'pass',lifecycleStatus:'baselined'}],requirementBaselines:[{id:'BL-1',projectId:'p',version:1,status:'active',requirementIds:['REQ-1']}],designs:[],runs:[]});

test('design workflow completes all evidence-producing engineering stages',async()=>{const db=approvedDb(),queue=new JobQueue({concurrency:4});registerWorkflowHandlers(queue,new AdapterRegistry(),db);const run=startDesignWorkflow(queue,db,{projectId:'p',prompt:'urban ev'});await executeAll(queue);syncRun(run,queue.jobs);assert.equal(run.status,'complete');assert.equal(run.progress,100);assert.equal(queue.jobs.filter(x=>x.runId===run.id).length,10);assert.equal(db.designs.length,1);assert.equal(db.designs[0].status,'virtually_validated');assert.deepEqual(db.designs[0].validation.checks,{simulations:true,manufacturing:true,requirements:true,range:true,cost:true,length:true})});

test('workflow creates drafts and stops at the human requirement baseline gate',async()=>{const db={requirements:[],requirementBaselines:[],designs:[],runs:[]},queue=new JobQueue({concurrency:2});registerWorkflowHandlers(queue,new AdapterRegistry(),db);const run=startDesignWorkflow(queue,db,{projectId:'p',prompt:'주행거리 420km 이상'});await executeAll(queue);syncRun(run,queue.jobs);assert.equal(run.status,'blocked');assert.equal(run.gate,'requirement_baseline');assert.equal(db.requirements.length,1);assert.equal(db.designs.length,0);assert.ok(queue.jobs.slice(1).every(x=>x.status==='blocked'))});
test('failed constraints trigger a bounded derived design and complete revalidation',async()=>{const db=approvedDb(),queue=new JobQueue({concurrency:4});registerWorkflowHandlers(queue,new AdapterRegistry(),db);const run=startDesignWorkflow(queue,db,{projectId:'p',prompt:'urban ev',parameters:{length:4200,wheelbase:2630,height:1570,wheel:19}});await executeAll(queue);syncRun(run,queue.jobs);assert.equal(run.status,'complete');assert.equal(run.iteration,2);assert.equal(db.designs.length,2);assert.equal(db.designs[0].status,'improvement_required');assert.equal(db.designs[1].parentDesignId,db.designs[0].id);assert.equal(db.designs[1].parameters.length,4000);assert.equal(db.designs[1].status,'virtually_validated');assert.equal(queue.jobs.filter(x=>x.runId===run.id).length,19)});
test('optimization stagnation is escalated instead of reported as complete',async()=>{const db=approvedDb(),queue=new JobQueue({concurrency:4});registerWorkflowHandlers(queue,new AdapterRegistry(),db);const run=startDesignWorkflow(queue,db,{projectId:'p',prompt:'impossible cost target',parameters:{length:3990,wheelbase:2630,height:1570,wheel:19,capacity:120}});await executeAll(queue);syncRun(run,queue.jobs);assert.equal(run.status,'needs_review');assert.equal(run.stage,'expert_handoff');assert.equal(run.gate,'optimization_stagnation');assert.equal(run.iteration,3);assert.equal(db.designs.at(-1).status,'stagnated');assert.equal(db.designs.length,3)});
test('human decision resumes a terminal run with immutable parent lineage',async()=>{const db={requirements:[],requirementBaselines:[],designs:[],runs:[]},queue=new JobQueue({concurrency:4});registerWorkflowHandlers(queue,new AdapterRegistry(),db);const blocked=startDesignWorkflow(queue,db,{projectId:'p',prompt:'주행거리 420km 이상',parameters:{length:3990}});await executeAll(queue);syncRun(blocked,queue.jobs);const requirement=db.requirements[0];requirement.lifecycleStatus='baselined';requirement.status='pass';db.requirementBaselines.push({id:'BL-HUMAN',projectId:'p',version:1,status:'active',requirementIds:[requirement.id]});const resumed=resumeDesignWorkflow(queue,db,blocked.id,{parameters:{length:3990,capacity:82},actor:'lead',reason:'baseline_approved'});assert.equal(resumed.parentRunId,blocked.id);assert.equal(blocked.resumedByRunId,resumed.id);assert.throws(()=>resumeDesignWorkflow(queue,db,blocked.id),/run_already_resumed/);await executeAll(queue);syncRun(resumed,queue.jobs);assert.equal(resumed.status,'complete');assert.equal(resumed.resumeReason,'baseline_approved')});
