import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { ArtifactStore } from './artifacts.js';
import { assessRelease, createRelease } from './release.js';

const completeDb=()=>({projects:[{id:'p',code:'P',name:'Project',organizationId:'o'}],requirements:[{id:'r',projectId:'p',title:'Range',priority:'must',status:'pass'}],goals:[{id:'SAFETY-1',projectId:'p',actual:0}],designs:[{id:'d',projectId:'p',name:'Design',metrics:{range:420}}],simulations:['aero','thermal','structure','range'].map(type=>({id:`s-${type}`,projectId:'p',designId:'d',type,name:type,status:'complete'})),evidence:[],changes:[],knowledge:[],manufacturingEvaluations:[{projectId:'p',designId:'d',manufacturable:true,cost:{total:10}}],physicalTests:[{id:'t',projectId:'p',designId:'d',type:'road',metric:'range',status:'complete'}],approvals:[{id:'a',projectId:'p',targetId:'d',grade:'S5',status:'approved'}],complianceAssessments:[{id:'cmp',projectId:'p',designId:'d',compliant:true,rules:[]}],bom:[],artifacts:[],designReleases:[]});
test('release assessment identifies all required gates',()=>{const db=completeDb();assert.equal(assessRelease(db,'p','d').releasable,true);db.approvals=[];assert.deepEqual(assessRelease(db,'p','d').missing,['approval'])});
test('release creates content-addressed ZIP artifact and record',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'af-release-test-'));try{const db=completeDb(),store=new ArtifactStore({root,metadata:db.artifacts}),release=createRelease(db,{projectId:'p',designId:'d',artifactStore:store,actor:'u'}),artifact=store.find(release.artifactId),zip=fs.readFileSync(store.pathFor(artifact));assert.equal(release.status,'released');assert.equal(release.complianceAssessmentId,'cmp');assert.equal(artifact.mimeType,'application/zip');assert.equal(store.verify(artifact),true);assert.equal(zip.readUInt32LE(0),0x04034b50);assert.ok(zip.includes(Buffer.from('pre-compliance.json')))}finally{fs.rmSync(root,{recursive:true,force:true})}});
test('release package is blocked when physical evidence is missing',()=>{const db=completeDb();db.physicalTests=[];assert.throws(()=>createRelease(db,{projectId:'p',designId:'d',artifactStore:{},actor:'u'}),e=>e.code==='release_gate_failed'&&e.missing.includes('physical'))});
test('optimized release includes reproducible search provenance',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'af-release-test-'));try{const db=completeDb();db.designs[0].optimizationRunId='opt';db.designs[0].optimizationCandidateId='c1';db.optimizationRuns=[{id:'opt',algorithm:'halton-pareto-rom-1.0',seed:42,weights:{range:.5},constraints:[],parentDesignId:'base',candidates:[{id:'c1',parameters:{length:3990}}]}];const store=new ArtifactStore({root,metadata:db.artifacts}),release=createRelease(db,{projectId:'p',designId:'d',artifactStore:store,actor:'u'}),zip=fs.readFileSync(store.pathFor(store.find(release.artifactId)));assert.ok(zip.includes(Buffer.from('optimization-provenance.json')));assert.ok(zip.includes(Buffer.from('halton-pareto-rom-1.0')))}finally{fs.rmSync(root,{recursive:true,force:true})}});
