import crypto from 'node:crypto';
import fs from 'node:fs';
import { randomUUID } from 'node:crypto';
import { createProjectPdf } from './pdfReport.js';
import { createZip } from './zip.js';
import { buildKnowledgeGraph } from './knowledgeGraph.js';
import { activeRequirements } from './requirementLifecycle.js';
import { latestCompliance } from './compliance.js';
import { projectBom } from './bomScope.js';

export function assessRelease(db,projectId,designId){const requirements=activeRequirements(db,projectId).filter(x=>['must','critical'].includes(x.priority)),simulations=db.simulations.filter(x=>x.projectId===projectId&&x.designId===designId),manufacturing=db.manufacturingEvaluations.find(x=>x.projectId===projectId&&x.designId===designId),physical=db.physicalTests?.filter(x=>x.projectId===projectId&&x.designId===designId)||[],approval=db.approvals.find(x=>x.projectId===projectId&&x.targetId===designId&&x.grade==='S5'&&x.status==='approved'),compliance=latestCompliance(db,projectId,designId),graph=buildKnowledgeGraph(db,projectId),safetyGoals=db.goals.filter(x=>x.projectId===projectId&&x.id.startsWith('SAFETY'));const checks={requirements:requirements.length>0&&requirements.every(x=>x.status==='pass'),simulations:['aero','thermal','structure','range'].every(type=>simulations.some(x=>x.type===type&&x.status==='complete')),manufacturing:Boolean(manufacturing?.manufacturable),physical:physical.length>0&&physical.every(x=>x.status==='complete'),traceability:graph.stats.traceability===1,approval:Boolean(approval),safety:Boolean(compliance?.compliant)&&safetyGoals.every(x=>x.actual===0)};return{releasable:Object.values(checks).every(Boolean),checks,missing:Object.entries(checks).filter(([,v])=>!v).map(([k])=>k),requirements,manufacturing,physical,simulations,graph,approval,compliance}}
export function createRelease(db,{projectId,designId,artifactStore,actor}){const assessment=assessRelease(db,projectId,designId);if(!assessment.releasable)throw Object.assign(new Error('release_gate_failed'),{code:'release_gate_failed',missing:assessment.missing});const project=db.projects.find(x=>x.id===projectId),design=db.designs.find(x=>x.id===designId),requirements=assessment.requirements,bom=projectBom(db,projectId),pdf=createProjectPdf({project,design,requirements,simulations:assessment.simulations,manufacturing:assessment.manufacturing,physicalTests:assessment.physical}),bomCsv=['partNo,description,system,qty,unitCost',...bom.map(x=>[x.partNo,x.description,x.system,x.qty,x.unitCost].map(csv).join(','))].join('\n'),files=[{name:'report.pdf',data:pdf},{name:'design-spec.json',data:JSON.stringify({project,design,requirements},null,2)},{name:'bom.csv',data:bomCsv},{name:'traceability.json',data:JSON.stringify(assessment.graph,null,2)},{name:'pre-compliance.json',data:JSON.stringify(assessment.compliance,null,2)}],optimization=(db.optimizationRuns||[]).find(x=>x.id===design.optimizationRunId);if(optimization)files.push({name:'optimization-provenance.json',data:JSON.stringify({id:optimization.id,algorithm:optimization.algorithm,seed:optimization.seed,weights:optimization.weights,constraints:optimization.constraints,parentDesignId:optimization.parentDesignId,candidateId:design.optimizationCandidateId,candidate:optimization.candidates.find(x=>x.id===design.optimizationCandidateId)},null,2)});for(const a of db.artifacts.filter(x=>x.projectId===projectId&&x.kind!=='release_package'))if(artifactStore.verify(a))files.push({name:`artifacts/${a.id}-${a.name}`,data:fs.readFileSync(artifactStore.pathFor(a))});const manifest={releaseId:randomUUID(),projectId,designId,createdAt:new Date().toISOString(),createdBy:actor,complianceAssessmentId:assessment.compliance.id,files:files.map(f=>({name:f.name,size:Buffer.byteLength(f.data),sha256:crypto.createHash('sha256').update(f.data).digest('hex')}))};files.push({name:'manifest.json',data:JSON.stringify(manifest,null,2)});const zip=createZip(files),artifact=artifactStore.put(zip,{projectId,organizationId:project.organizationId,name:`${project.code}-${design.id}-release.zip`,mimeType:'application/zip',kind:'release_package',createdBy:actor}),release={...manifest,artifactId:artifact.id,status:'released',approvalId:assessment.approval.id};db.designReleases.unshift(release);return release}
const csv=v=>`"${String(v??'').replace(/"/g,'""')}"`;
