import test from 'node:test';
import assert from 'node:assert/strict';
import { activeRequirements, approveRequirement, createRequirementBaseline, createRequirementDrafts, reviseRequirement, verifyRequirement } from './requirementLifecycle.js';

const fresh=()=>({requirements:[],requirementBaselines:[],requirementVerifications:[],verificationTasks:[],designs:[{id:'d1',projectId:'p'}],simulations:[],physicalTests:[],manufacturingEvaluations:[],engineExecutions:[],evidence:[],changes:[]});
test('natural language drafts preserve source and require explicit approval',()=>{const db=fresh(),result=createRequirementDrafts(db,{projectId:'p',text:'4인승 전기차, 전장 4m 이하, 주행거리 420km 이상, 제조원가 3천만원 이하.',actor:'u'});assert.equal(result.drafts.length,4);assert.ok(result.drafts.every(x=>x.lifecycleStatus==='draft'&&x.sourceText));assert.equal(activeRequirements(db,'p').length,0);for(const item of result.drafts)approveRequirement(db,item.id,{actor:'reviewer'});assert.ok(result.drafts.every(x=>x.approvedBy==='reviewer'))});
test('approved requirements create a hashed immutable baseline',()=>{const db=fresh(),drafts=createRequirementDrafts(db,{projectId:'p',text:'전장 4m 이하, 주행거리 420km 이상.'}).drafts;drafts.forEach(x=>approveRequirement(db,x.id));const {baseline}=createRequirementBaseline(db,{projectId:'p',requirementIds:drafts.map(x=>x.id),actor:'lead'});assert.equal(baseline.version,1);assert.match(baseline.sha256,/^[a-f0-9]{64}$/);assert.equal(activeRequirements(db,'p').length,2);assert.ok(drafts.every(x=>x.lifecycleStatus==='baselined'))});
test('revision baseline creates field diff and revalidation work',()=>{const db=fresh(),draft=createRequirementDrafts(db,{projectId:'p',text:'주행거리 420km 이상.'}).drafts[0];approveRequirement(db,draft.id);createRequirementBaseline(db,{projectId:'p',requirementIds:[draft.id]});const revised=reviseRequirement(db,draft.id,{target:450},{actor:'energy'});assert.deepEqual(revised.diff.map(x=>x.field),['target']);approveRequirement(db,revised.requirement.id);const result=createRequirementBaseline(db,{projectId:'p',requirementIds:[revised.requirement.id],actor:'lead'});assert.equal(result.baseline.version,2);assert.equal(result.impact.changes[0].diff[0].before,420);assert.equal(result.impact.verificationTasks.length,2);assert.deepEqual(result.impact.affectedDesignIds,['d1']);assert.equal(draft.lifecycleStatus,'superseded')});
test('baselined requirement needs real compatible evidence and closes its revalidation work',()=>{const db=fresh(),draft=createRequirementDrafts(db,{projectId:'p',text:'주행거리 420km 이상.'}).drafts[0];approveRequirement(db,draft.id);createRequirementBaseline(db,{projectId:'p',requirementIds:[draft.id]});assert.throws(()=>verifyRequirement(db,draft.id,{status:'pass'}),error=>error.code==='verification_evidence_required');assert.throws(()=>verifyRequirement(db,draft.id,{status:'pass',evidenceId:'FAKE'}),error=>error.code==='verification_evidence_not_found');db.simulations.push({id:'SIM-AERO-1',projectId:'p',type:'aero',status:'complete'},{id:'SIM-RANGE-1',projectId:'p',type:'range',status:'complete'});db.evidence.push({id:'EVD-AERO',projectId:'p',type:'simulation',sourceId:'SIM-AERO-1',confidence:.98});assert.throws(()=>verifyRequirement(db,draft.id,{status:'pass',evidenceId:'EVD-AERO'}),error=>error.code==='verification_evidence_incompatible');const result=verifyRequirement(db,draft.id,{status:'pass',evidenceId:'SIM-RANGE-1',actor:'validator'});assert.equal(result.requirement.status,'pass');assert.equal(result.verification.evidenceType,'simulation.range')});
test('hard conflicts prevent approval and baseline',()=>{const db=fresh();db.requirements.push({id:'REQ-001',logicalId:'REQ-001',projectId:'p',category:'performance',title:'Range max',operator:'≤',target:300,unit:'km',priority:'must',lifecycleStatus:'baselined'});const draft=createRequirementDrafts(db,{projectId:'p',text:'주행거리 420km 이상.'}).drafts[0];assert.throws(()=>approveRequirement(db,draft.id),error=>error.code==='requirement_conflict')});
test('contract rejects empty briefs and duplicate baseline selections',()=>{const db=fresh();assert.throws(()=>createRequirementDrafts(db,{projectId:'p',text:'  '}),error=>error.code==='requirement_text_required');const draft=createRequirementDrafts(db,{projectId:'p',text:'주행거리 420km 이상.'}).drafts[0];approveRequirement(db,draft.id);assert.throws(()=>createRequirementBaseline(db,{projectId:'p',requirementIds:[draft.id,draft.id]}),error=>error.code==='baseline_duplicate_requirements')});
test('cost evidence remains valid when an unrelated DFM rule fails',()=>{const db=fresh(),draft=createRequirementDrafts(db,{projectId:'p',text:'제조원가 3천만원 이하.'}).drafts[0];approveRequirement(db,draft.id);createRequirementBaseline(db,{projectId:'p',requirementIds:[draft.id]});db.manufacturingEvaluations.push({id:'MFG-1',projectId:'p',manufacturable:false,cost:{total:29000000},issues:[{code:'vehicle_length_limit'}]});const result=verifyRequirement(db,draft.id,{status:'pass',evidenceId:'MFG-1'});assert.equal(result.verification.evidenceType,'manufacturing')});
