import crypto from 'node:crypto';
import { randomUUID } from 'node:crypto';
import { detectConflicts, refineRequirements } from './requirements.js';

const trackedFields=['title','category','operator','target','unit','priority','verification'];
const verificationByCategory={dimension:['cad_measurement','dimensional_scan'],performance:['energy_consumption_cycle','certified_drive_cycle'],cost:['bom_cost_rollup','supplier_quote'],package:['occupant_package_check','ergonomic_buck']};
const digest=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const nextRequirementId=db=>`REQ-${String(Math.max(0,...db.requirements.map(x=>Number(String(x.id).match(/REQ-(\d+)/)?.[1])||0))+1).padStart(3,'0')}`;

export function createRequirementDrafts(db,{projectId,text,actor='system'}){if(!projectId||!String(text||'').trim())throw lifecycleError('requirement_text_required');const refined=refineRequirements(text,projectId),batchId=randomUUID(),drafts=refined.requirements.map(item=>{const id=nextRequirementId(db),requirement={id,logicalId:id,revision:1,lifecycleStatus:'draft',status:'pending',batchId,createdAt:new Date().toISOString(),createdBy:actor,...item};db.requirements.push(requirement);return requirement}),conflicts=detectConflicts([...activeRequirements(db,projectId),...drafts]);return{batchId,drafts,ambiguities:refined.ambiguities,conflicts,confidence:refined.confidence,readyForReview:drafts.length>0&&!conflicts.some(x=>x.type==='hard_conflict')&&!refined.ambiguities.length}}
export function approveRequirement(db,id,{actor='system'}={}){const item=db.requirements.find(x=>x.id===id);if(!item)throw lifecycleError('requirement_not_found');if(item.lifecycleStatus!=='draft')throw lifecycleError('requirement_not_draft');const conflicts=detectConflicts([...activeRequirements(db,item.projectId).filter(x=>x.logicalId!==item.logicalId),item]);if(conflicts.some(x=>x.type==='hard_conflict'))throw lifecycleError('requirement_conflict',{conflicts});item.lifecycleStatus='approved';item.approvedAt=new Date().toISOString();item.approvedBy=actor;return item}
export function reviseRequirement(db,id,patch,{actor='system'}={}){const source=db.requirements.find(x=>x.id===id);if(!source)throw lifecycleError('requirement_not_found');const allowed=Object.fromEntries(Object.entries(patch||{}).filter(([key])=>trackedFields.includes(key))),revision=Math.max(...db.requirements.filter(x=>x.logicalId===(source.logicalId||source.id)).map(x=>x.revision||1))+1,item={...source,...allowed,id:nextRequirementId(db),logicalId:source.logicalId||source.id,revision,lifecycleStatus:'draft',status:'pending',supersedesId:source.id,createdAt:new Date().toISOString(),createdBy:actor,approvedAt:null,approvedBy:null,baselineId:null};db.requirements.push(item);return{requirement:item,diff:diffRequirement(source,item)}}
export function createRequirementBaseline(db,{projectId,requirementIds,actor='system'}){db.requirementBaselines??=[];db.verificationTasks??=[];if(requirementIds?.length!==new Set(requirementIds||[]).size)throw lifecycleError('baseline_duplicate_requirements');const previous=db.requirementBaselines.find(x=>x.projectId===projectId&&x.status==='active');let selected=(requirementIds?.length?requirementIds.map(id=>db.requirements.find(x=>x.id===id)):db.requirements.filter(x=>x.projectId===projectId&&x.lifecycleStatus==='approved')).filter(Boolean);if(previous&&requirementIds?.length){const replaced=new Set(selected.map(x=>x.logicalId||x.id));selected=[...selected,...previous.requirementIds.map(id=>db.requirements.find(x=>x.id===id)).filter(x=>x&&!replaced.has(x.logicalId||x.id))]}if(!selected.length)throw lifecycleError('baseline_empty');if(selected.some(x=>x.projectId!==projectId||!['approved','baselined'].includes(x.lifecycleStatus)))throw lifecycleError('baseline_requires_approval');const conflicts=detectConflicts(selected);if(conflicts.some(x=>x.type==='hard_conflict'))throw lifecycleError('baseline_conflict',{conflicts});const version=(previous?.version||0)+1,snapshot=selected.map(x=>Object.fromEntries(['id','logicalId','revision',...trackedFields].map(key=>[key,x[key]]))),baseline={id:randomUUID(),projectId,version,status:'active',requirementIds:selected.map(x=>x.id),snapshot,sha256:digest(snapshot),createdAt:new Date().toISOString(),createdBy:actor};if(previous)previous.status='superseded';for(const item of selected){item.baselineId=baseline.id;item.lifecycleStatus='baselined';for(const old of db.requirements.filter(x=>x.logicalId===item.logicalId&&x.id!==item.id&&['approved','baselined'].includes(x.lifecycleStatus)))old.lifecycleStatus='superseded'}db.requirementBaselines.unshift(baseline);const impact=previous?createBaselineImpact(db,previous,baseline,actor):{changes:[],affectedDesignIds:[],verificationTasks:[]};baseline.impact=impact;return{baseline,impact}}
export function activeRequirements(db,projectId){const baseline=db.requirementBaselines?.find(x=>x.projectId===projectId&&x.status==='active');if(baseline)return baseline.requirementIds.map(id=>db.requirements.find(x=>x.id===id)).filter(Boolean);return db.requirements.filter(x=>x.projectId===projectId&&!['draft','superseded'].includes(x.lifecycleStatus))}
export function verifyRequirement(db,id,{status,evidenceId,actor='system'}={}){const item=db.requirements.find(x=>x.id===id);if(!item)throw lifecycleError('requirement_not_found');if(item.lifecycleStatus!=='baselined')throw lifecycleError('requirement_not_baselined');if(!['pass','fail'].includes(status))throw lifecycleError('verification_status_invalid');if(!evidenceId)throw lifecycleError('verification_evidence_required');const evidence=resolveVerificationEvidence(db,item,evidenceId);if(!evidence)throw lifecycleError('verification_evidence_not_found');if(!evidence.compatible)throw lifecycleError('verification_evidence_incompatible',{category:item.category,evidenceType:evidence.type});db.requirementVerifications??=[];const record={id:randomUUID(),projectId:item.projectId,requirementId:id,baselineId:item.baselineId,status,evidenceId,evidenceType:evidence.type,verifiedAt:new Date().toISOString(),verifiedBy:actor};db.requirementVerifications.unshift(record);item.status=status;item.verificationEvidenceId=evidenceId;item.verifiedAt=record.verifiedAt;for(const task of db.verificationTasks?.filter(x=>x.requirementId===id&&x.status!=='complete')||[]){task.status='complete';task.evidenceId=evidenceId;task.completedAt=record.verifiedAt}return{requirement:item,verification:record}}
export function diffRequirement(before,after){const changes=[];for(const field of trackedFields)if(JSON.stringify(before[field])!==JSON.stringify(after[field]))changes.push({field,before:before[field],after:after[field]});return changes}
function createBaselineImpact(db,previous,current,actor){const before=new Map(previous.snapshot.map(x=>[x.logicalId||x.id,x])),after=new Map(current.snapshot.map(x=>[x.logicalId||x.id,x])),changes=[];for(const key of new Set([...before.keys(),...after.keys()])){const old=before.get(key),next=after.get(key),diff=old&&next?diffRequirement(old,next):[{field:'requirement',before:old,after:next}];if(diff.length)changes.push({logicalId:key,beforeId:old?.id,afterId:next?.id,diff})}const affectedDesignIds=db.designs.filter(x=>x.projectId===current.projectId).map(x=>x.id),verificationTasks=[];for(const change of changes){const requirement=after.get(change.logicalId);for(const method of verificationByCategory[requirement?.category]||['design_review']){const task={id:randomUUID(),projectId:current.projectId,baselineId:current.id,requirementId:requirement?.id,method,status:'queued',affectedDesignIds,createdAt:new Date().toISOString(),createdBy:actor};db.verificationTasks.push(task);verificationTasks.push(task)}}if(changes.length)db.changes.unshift({id:randomUUID(),projectId:current.projectId,type:'requirements.baseline_changed',target:current.id,source:previous.id,at:new Date().toISOString(),actor,changes,affectedDesignIds,verificationTaskIds:verificationTasks.map(x=>x.id)});return{changes,affectedDesignIds,verificationTasks}}
function resolveVerificationEvidence(db,requirement,id){const projectId=requirement.projectId,category=requirement.category;const simulation=db.simulations?.find(x=>x.id===id&&x.projectId===projectId&&x.status==='complete');if(simulation)return{type:`simulation.${simulation.type}`,compatible:category===simulation.type||(category==='performance'&&simulation.type==='range')||(category==='package'&&simulation.type==='structure')};const physical=db.physicalTests?.find(x=>x.id===id&&x.projectId===projectId&&x.status==='complete');if(physical)return{type:`physical.${physical.type}`,compatible:['performance','dimension','package','aero'].includes(category)};const manufacturing=db.manufacturingEvaluations?.find(x=>x.id===id&&x.projectId===projectId);if(manufacturing)return{type:'manufacturing',compatible:category==='cost'};const execution=db.engineExecutions?.find(x=>x.id===id&&x.projectId===projectId&&x.status==='succeeded');if(execution)return{type:`engine.${execution.action}`,compatible:['dimension','package'].includes(category)&&execution.action==='vehicle.generate'};const record=db.evidence?.find(x=>x.id===id&&x.projectId===projectId&&Number(x.confidence||0)>=.8);if(record){const source=record.sourceId&&record.sourceId!==id?resolveVerificationEvidence(db,requirement,record.sourceId):null;return{type:`evidence.${record.type}`,compatible:Boolean(source?.compatible||record.category===category)}}return null}
const lifecycleError=(code,details)=>Object.assign(new Error(code),{code,details});
