import test from 'node:test';
import assert from 'node:assert/strict';
import { RobotGateway } from './robotGateway.js';

const cell=()=>({id:'c',projectId:'p',state:'idle',interlocks:{emergencyStop:true,cellClear:true,guardClosed:true,sensorsHealthy:true}}),approval={id:'a',projectId:'p',targetId:'c',grade:'S4',status:'approved'};
test('approved interlocked command is dispatched and idempotent',async()=>{const commands=[],gateway=new RobotGateway({commands,cells:[cell()]});const one=await gateway.submit({projectId:'p',cellId:'c',action:'robot.test',approval,idempotencyKey:'key-1',actor:'u'}),two=await gateway.submit({projectId:'p',cellId:'c',action:'robot.test',approval,idempotencyKey:'key-1',actor:'u'});assert.equal(one.status,'dispatched');assert.equal(one.id,two.id);assert.equal(commands.length,1)});
test('missing approval and failed interlock block physical action',async()=>{const gateway=new RobotGateway({cells:[cell()]});await assert.rejects(()=>gateway.submit({projectId:'p',cellId:'c',action:'robot.test',idempotencyKey:'x'}),e=>e.code==='s4_approval_required');const broken=cell();broken.interlocks.guardClosed=false;await assert.rejects(()=>new RobotGateway({cells:[broken]}).submit({projectId:'p',cellId:'c',action:'robot.test',approval,idempotencyKey:'y'}),e=>e.code==='interlock_failure')});
test('emergency stop cancels active command and locks cell',async()=>{const c=cell(),gateway=new RobotGateway({cells:[c],commands:[]});const command=await gateway.submit({projectId:'p',cellId:'c',action:'robot.test',approval,idempotencyKey:'run'});gateway.emergencyStop('c','operator','temperature','stop');assert.equal(command.status,'cancelled');assert.equal(c.state,'emergency_stopped');assert.equal(c.interlocks.emergencyStop,false)});
test('acknowledgement returns cell to idle',async()=>{const c=cell(),gateway=new RobotGateway({cells:[c],commands:[]}),command=await gateway.submit({projectId:'p',cellId:'c',action:'robot.inspect',approval,idempotencyKey:'inspect'});gateway.acknowledge(command.id,{status:'completed',result:{pass:true}});assert.equal(c.state,'idle');assert.equal(command.result.pass,true)});
test('S4 approval is scoped to the exact physical cell',async()=>{const gateway=new RobotGateway({cells:[cell()]});await assert.rejects(()=>gateway.submit({projectId:'p',cellId:'c',action:'robot.test',approval:{...approval,targetId:'other'},idempotencyKey:'wrong-cell'}),e=>e.code==='s4_approval_required')});
test('emergency stop is idempotent and unknown interlocks are rejected',()=>{const commands=[],gateway=new RobotGateway({cells:[cell()],commands});const one=gateway.emergencyStop('c','operator','test','stop-key'),two=gateway.emergencyStop('c','operator','test','stop-key');assert.equal(one.id,two.id);assert.equal(commands.length,1);assert.throws(()=>gateway.updateInterlocks('c',{bypass:true},'operator'),e=>e.code==='invalid_interlock')});
