import { randomUUID } from 'node:crypto';

const allowedActions=new Set(['robot.prototype','robot.test','robot.inspect','robot.stop','robot.home']);
export class RobotGateway{
  constructor({commands=[],cells=[],transport=async command=>({accepted:true,externalId:`ROS-${command.id}`}),clock=()=>new Date().toISOString()}={}){this.commands=commands;this.cells=cells;this.transport=transport;this.clock=clock}
  cell(id){return this.cells.find(x=>x.id===id)}
  async submit({projectId,cellId,action,parameters={},approval,idempotencyKey,actor}){if(!idempotencyKey)throw failure('idempotency_key_required');const existing=this.commands.find(x=>x.idempotencyKey===idempotencyKey);if(existing)return existing;if(!allowedActions.has(action))throw failure('action_not_allowed');const cell=this.cell(cellId);if(!cell||cell.projectId!==projectId)throw failure('cell_not_found');if(action==='robot.stop')return this.emergencyStop(cellId,actor,'operator_request',idempotencyKey);if(approval?.grade!=='S4'||approval?.status!=='approved'||approval?.projectId!==projectId||approval?.targetId!==cellId)throw failure('s4_approval_required');const failed=Object.entries(cell.interlocks||{}).filter(([,v])=>v!==true).map(([k])=>k);if(failed.length)throw failure('interlock_failure',{failed});if(!['idle','ready'].includes(cell.state))throw failure('cell_not_ready',{state:cell.state});const command={id:randomUUID(),projectId,cellId,action,parameters,approvalId:approval.id,idempotencyKey,actor,status:'safety_checked',createdAt:this.clock(),history:[{state:'requested',at:this.clock()},{state:'safety_checked',at:this.clock()}]};this.commands.unshift(command);cell.state='running';cell.updatedAt=this.clock();try{const result=await this.transport(command);command.status='dispatched';command.externalId=result.externalId;command.history.push({state:'dispatched',at:this.clock()});return command}catch(error){command.status='failed';command.error=error.message;command.history.push({state:'failed',at:this.clock()});cell.state='fault';throw error}}
  acknowledge(id,{status,result}){const command=this.commands.find(x=>x.id===id);if(!command)throw failure('command_not_found');if(!['completed','failed','cancelled'].includes(status))throw failure('invalid_ack_status');command.status=status;command.result=result;command.completedAt=this.clock();command.history.push({state:status,at:this.clock()});const cell=this.cell(command.cellId);cell.state=status==='completed'?'idle':'fault';cell.updatedAt=this.clock();return command}
  emergencyStop(cellId,actor,reason='safety_event',idempotencyKey=randomUUID()){const existing=this.commands.find(x=>x.idempotencyKey===idempotencyKey);if(existing)return existing;const cell=this.cell(cellId);if(!cell)throw failure('cell_not_found');cell.state='emergency_stopped';cell.interlocks.emergencyStop=false;cell.updatedAt=this.clock();for(const c of this.commands.filter(x=>x.cellId===cellId&&['safety_checked','dispatched'].includes(x.status))){c.status='cancelled';c.history.push({state:'cancelled',reason,at:this.clock()})}const command={id:randomUUID(),projectId:cell.projectId,cellId,action:'robot.stop',idempotencyKey,actor,status:'completed',createdAt:this.clock(),completedAt:this.clock(),history:[{state:'emergency_stop',reason,at:this.clock()}]};this.commands.unshift(command);return command}
  updateInterlocks(cellId,interlocks,actor){const allowed=new Set(['emergencyStop','cellClear','guardClosed','sensorsHealthy']);const unknown=Object.keys(interlocks||{}).filter(key=>!allowed.has(key));if(unknown.length)throw failure('invalid_interlock',{unknown});const cell=this.cell(cellId);if(!cell)throw failure('cell_not_found');cell.interlocks={...cell.interlocks,...interlocks};cell.updatedAt=this.clock();cell.updatedBy=actor;if(Object.values(cell.interlocks).every(Boolean)&&cell.state==='emergency_stopped')cell.state='ready';return cell}
}
const failure=(code,details={})=>Object.assign(new Error(code),{type:'safety_failure',code,details});
