import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const safe=value=>{if(!/^[a-zA-Z0-9_.-]+$/.test(value))throw new Error('invalid time-series identifier');return value};
export class TimeSeriesStore{
  constructor({root=process.env.AUTOFORGE_TIMESERIES_DIR||path.resolve('data','timeseries'),streams=[]}={}){this.root=root;this.streams=streams;this.recentKeys=new Set();fs.mkdirSync(root,{recursive:true})}
  ingest({projectId,vehicleId,sensorId,signal,unit,samples,calibration}){[projectId,vehicleId,sensorId,signal].forEach(safe);if(!Array.isArray(samples)||!samples.length||samples.length>10000)throw new Error('samples must contain 1..10000 readings');if(!calibration?.validUntil||new Date(calibration.validUntil)<=new Date())throw new Error('sensor calibration is missing or expired');const accepted=[],rejected=[];for(const [index,s] of samples.entries()){const timestamp=new Date(s.timestamp);if(!Number.isFinite(Number(s.value))||Number.isNaN(timestamp.getTime())||timestamp>Date.now()+300000){rejected.push({index,reason:'invalid_sample'});continue}const key=crypto.createHash('sha1').update(`${sensorId}|${timestamp.toISOString()}|${s.sequence??''}`).digest('hex');if(this.recentKeys.has(key)){rejected.push({index,reason:'duplicate'});continue}this.recentKeys.add(key);if(this.recentKeys.size>50000)this.recentKeys.clear();accepted.push({timestamp:timestamp.toISOString(),value:Number(s.value),sequence:s.sequence??null,quality:quality(s),sensorId,signal,unit})}
    for(const sample of accepted){const day=sample.timestamp.slice(0,10),dir=path.join(this.root,safe(projectId),safe(vehicleId),safe(signal));fs.mkdirSync(dir,{recursive:true});fs.appendFileSync(path.join(dir,`${day}.ndjson`),`${JSON.stringify(sample)}\n`)}
    let stream=this.streams.find(x=>x.projectId===projectId&&x.vehicleId===vehicleId&&x.sensorId===sensorId&&x.signal===signal);if(!stream){stream={id:crypto.randomUUID(),projectId,vehicleId,sensorId,signal,unit,createdAt:new Date().toISOString(),sampleCount:0};this.streams.push(stream)}stream.sampleCount+=accepted.length;stream.lastTimestamp=accepted.at(-1)?.timestamp||stream.lastTimestamp;stream.calibration=calibration;return{stream,accepted:accepted.length,rejected,total:samples.length};}
  query({projectId,vehicleId,signal,from,to,maxPoints=1000}){[projectId,vehicleId,signal].forEach(safe);const dir=path.join(this.root,projectId,vehicleId,signal);if(!fs.existsSync(dir))return{samples:[],summary:null};const start=from?new Date(from):-Infinity,end=to?new Date(to):Infinity;let samples=[];for(const file of fs.readdirSync(dir).filter(x=>x.endsWith('.ndjson')).sort()){for(const line of fs.readFileSync(path.join(dir,file),'utf8').split('\n').filter(Boolean)){const sample=JSON.parse(line),t=new Date(sample.timestamp);if(t>=start&&t<=end)samples.push(sample)}}samples.sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const summary=summarize(samples);if(samples.length>maxPoints)samples=downsample(samples,maxPoints);return{samples,summary,total:summary?.count||0,returned:samples.length}}
  latest({projectId,vehicleId}){const streams=this.streams.filter(x=>x.projectId===projectId&&x.vehicleId===vehicleId&&x.lastTimestamp);return streams.map(s=>{const result=this.query({projectId,vehicleId,signal:s.signal,from:s.lastTimestamp,to:s.lastTimestamp,maxPoints:1});return result.samples[0]}).filter(Boolean)}
}
const quality=s=>{const flags=[];if(s.status&&s.status!=='ok')flags.push(s.status);if(s.uncertainty!=null&&s.uncertainty>.1)flags.push('high_uncertainty');return{valid:flags.length===0,flags,uncertainty:s.uncertainty??null}};
export function summarize(samples){if(!samples.length)return null;const values=samples.map(x=>x.value);return{count:values.length,min:Math.min(...values),max:Math.max(...values),avg:Number((values.reduce((a,b)=>a+b,0)/values.length).toFixed(6)),first:samples[0].timestamp,last:samples.at(-1).timestamp,invalid:samples.filter(x=>!x.quality.valid).length}}
export function downsample(samples,maxPoints){if(samples.length<=maxPoints)return samples;const size=Math.ceil(samples.length/maxPoints),result=[];for(let i=0;i<samples.length;i+=size){const bucket=samples.slice(i,i+size),summary=summarize(bucket);result.push({timestamp:bucket[Math.floor(bucket.length/2)].timestamp,value:summary.avg,min:summary.min,max:summary.max,count:summary.count,quality:{valid:summary.invalid===0,flags:summary.invalid?['aggregated_invalid']:[]}})}return result}
