import { estimateVehicle } from './engines.js';
import { normalizeVehicleParameters } from './vehicleCad.js';

const round=(value,digits=3)=>Number(value.toFixed(digits));
const csv=(headers,rows)=>[headers.join(','),...rows.map(row=>row.join(','))].join('\n')+'\n';
export const supportedSimulationTypes=['aero','thermal','structure','range'];

export function simulateVehicle(type,input={}){
  if(!supportedSimulationTypes.includes(type))throw Object.assign(new Error(`unsupported simulation type: ${type}`),{code:'simulation_type_unsupported'});
  const parameters=normalizeVehicleParameters(input.parameters),estimate={...estimateVehicle({...parameters,...input.parameters}),...input.metrics};
  return({aero,thermal,structure,range}[type])({parameters,estimate,input});
}

function envelope(type,result,table,assumptions,uncertaintyPercent,columns){return{type,fidelity:'reduced_order_physics',modelVersion:'autoforge-rom-1.0',result:{...result,confidence:round(1-uncertaintyPercent/100,2),uncertaintyPercent},assumptions,columns,csv:table}}
function aero({parameters:p,estimate:m}){const rho=1.225,area=p.width/1000*p.height/1000*.84,cd=m.cd,rows=[];for(let kph=0;kph<=140;kph+=10){const velocity=kph/3.6,drag=.5*rho*cd*area*velocity**2;rows.push([kph,round(drag,2),round(drag*velocity/1000,2)])}const drag100=rows.find(x=>x[0]===100)[1];return envelope('aero',{cd,frontalAreaM2:round(area),dragAreaM2:round(cd*area),dragAt100KphN:drag100,powerAt100KphKw:rows.find(x=>x[0]===100)[2]},csv(['speed_kph','drag_n','aero_power_kw'],rows),['steady incompressible air at 15 C','zero yaw','smooth road stance'],8,['speed_kph','drag_n','aero_power_kw'])}
function thermal({input}){const ambient=Number(input.options?.ambientC??25),chargeKw=Number(input.options?.chargeKw??180),mass=Number(input.options?.batteryMassKg??470),heatCapacity=900,coolingKw=6.5,lossFraction=.045,step=10,rows=[];let temperature=ambient;for(let seconds=0;seconds<=1800;seconds+=step){const heatKw=chargeKw*lossFraction,cooling=Math.max(0,coolingKw+(temperature-ambient)*.22),netW=(heatKw-cooling)*1000;temperature+=netW*step/(mass*heatCapacity);rows.push([seconds,round(temperature,2),round(heatKw,2),round(cooling,2)])}const peak=Math.max(...rows.map(x=>x[1]));return envelope('thermal',{peakCellTempC:peak,temperatureRiseC:round(peak-ambient,2),chargePowerKw:chargeKw,coolingCapacityKw:coolingKw},csv(['time_s','pack_temp_c','heat_generation_kw','cooling_kw'],rows),['lumped pack temperature','constant fast-charge power','active liquid cooling'],12,['time_s','pack_temp_c','heat_generation_kw','cooling_kw'])}
function structure({parameters:p,estimate:m,input}){const material=input.options?.material||'steel_al_hybrid',mass=m.weight||1628,wheelbase=p.wheelbase/1000,width=p.width/1000,stiffness=round(18500+width*4800+(2.75-wheelbase)*3200,0),loads=[1,1.5,2.5,3],rows=loads.map(g=>{const force=mass*9.81*g,bending=force*wheelbase/8,stress=bending/(.00042*width);return[g,round(force,0),round(bending,0),round(stress/1e6,2)]}),maxStress=Math.max(...rows.map(x=>x[3]));return envelope('structure',{torsionalStiffnessNmPerDeg:stiffness,firstModeHz:round(27+stiffness/6500,1),maxReducedStressMpa:maxStress,material},csv(['load_g','vertical_force_n','bending_moment_nm','reduced_stress_mpa'],rows),['equivalent beam body-in-white','linear elastic response','symmetric vertical loading'],15,['load_g','vertical_force_n','bending_moment_nm','reduced_stress_mpa'])}
function range({parameters:p,estimate:m,input}){const rho=1.225,area=p.width/1000*p.height/1000*.84,cd=m.cd,mass=m.weight||1628,crr=.0095,efficiency=.9,rows=[];let energyWh=0,distanceM=0,previous=0;for(let second=0;second<=1800;second+=5){const phase=second%300,speedKph=phase<80?phase*.75:phase<180?60+(phase-80)*.4:100-(phase-180)*.6,speed=Math.max(0,speedKph)/3.6,acceleration=(speed-previous)/5,rolling=mass*9.81*crr,aeroForce=.5*rho*cd*area*speed**2,traction=(rolling+aeroForce+mass*Math.max(acceleration,0))*speed/efficiency,regen=acceleration<0?mass*acceleration*speed*.62:0,powerW=Math.max(0,traction+regen);energyWh+=powerW*5/3600;distanceM+=speed*5;previous=speed;rows.push([second,round(speedKph,1),round(powerW/1000,2),round(energyWh,2),round(distanceM/1000,3)])}const consumption=energyWh/(distanceM/1000)*100/1000,capacity=Number(input.parameters?.capacity||78.4),usable=capacity*.92,wltp=usable/consumption*100;return envelope('range',{wltpKm:round(wltp,0),consumptionKwhPer100Km:round(consumption,1),usableBatteryKwh:round(usable,1),cycleDistanceKm:round(distanceM/1000,2)},csv(['time_s','speed_kph','battery_power_kw','energy_wh','distance_km'],rows),['synthetic mixed urban/highway cycle','fixed rolling resistance','62 percent regenerative braking'],10,['time_s','speed_kph','battery_power_kw','energy_wh','distance_km'])}
