async function request(path, options={}) {
  const token=localStorage.getItem('autoforge_token');
  const response=await fetch(`/api${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...options.headers}});
  if(!response.ok){const error=new Error((await response.json().catch(()=>({}))).error||`HTTP ${response.status}`);error.status=response.status;throw error}
  return response.json();
}
async function download(path,name){const token=localStorage.getItem('autoforge_token'),response=await fetch(`/api${path}`,{headers:{...(token?{Authorization:`Bearer ${token}`}:{})}});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||`HTTP ${response.status}`);const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=name||'autoforge-artifact';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function parseSseFrames(buffer,onFrame){let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);let event='message',data='';for(const line of frame.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();else if(line.startsWith('data:'))data+=`${data?'\n':''}${line.slice(5).trimStart()}`}if(data)onFrame(JSON.parse(data),event)}return buffer}
function subscribeRun(id,onEvent){const controller=new AbortController(),token=localStorage.getItem('autoforge_token');(async()=>{const response=await fetch(`/api/runs/${id}/stream`,{headers:{Accept:'text/event-stream',...(token?{Authorization:`Bearer ${token}`}:{})},signal:controller.signal});if(!response.ok)throw new Error(`stream HTTP ${response.status}`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const{value,done}=await reader.read();if(done)break;buffer=parseSseFrames(buffer+decoder.decode(value,{stream:true}),onEvent)}})().catch(error=>{if(error.name!=='AbortError')onEvent({status:'failed',error:error.message},'run')});return()=>controller.abort()}
export const api={
  health:()=>request('/health'),
  projects:()=>request('/projects'),
  createProject:body=>request('/projects',{method:'POST',body:JSON.stringify(body)}),
  agents:()=>request('/agents'),
  agentCatalog:()=>request('/agents/catalog'),
  createAgent:body=>request('/agents',{method:'POST',body:JSON.stringify(body)}),
  updateAgent:(id,body)=>request(`/agents/${id}`,{method:'PATCH',body:JSON.stringify(body)}),
  mcpTools:()=>request('/mcp/tools'),
  login:async(email,password)=>{const result=await request('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('autoforge_token',result.token);return result},
  me:()=>request('/auth/me'),
  logout:async()=>{try{await request('/auth/logout',{method:'POST',body:'{}'})}finally{localStorage.removeItem('autoforge_token')}},
  graph:(projectId='urban-e04')=>request(`/projects/${projectId}/graph`),
  downloadArtifact:(id,name)=>download(`/artifacts/${id}/download`,name),
  architectures:(projectId='urban-e04')=>request(`/architectures?projectId=${encodeURIComponent(projectId)}`),
  saveArchitecture:body=>request('/architectures',{method:'POST',body:JSON.stringify(body)}),
  estimate:parameters=>request('/designs/estimate',{method:'POST',body:JSON.stringify(parameters)}),
  createDesign:body=>request('/designs',{method:'POST',body:JSON.stringify(body)}),
  generateVariants:(designId,count=6)=>request(`/designs/${designId}/variants`,{method:'POST',body:JSON.stringify({count})}),
  generateCad:designId=>request(`/designs/${designId}/cad`,{method:'POST',body:'{}'}),
  startRun:(prompt,projectId='urban-e04')=>request('/runs',{method:'POST',body:JSON.stringify({prompt,projectId})}),
  runs:(projectId='urban-e04')=>request(`/runs?projectId=${encodeURIComponent(projectId)}`),
  resumeRun:(id,parameters,reason='human_review')=>request(`/runs/${id}/resume`,{method:'POST',body:JSON.stringify({parameters,reason})}),
  run:id=>request(`/runs/${id}`),
  subscribeRun,
  simulate:(type,designId)=>request('/simulations',{method:'POST',body:JSON.stringify({type,designId})}),
  simulations:(projectId='urban-e04')=>request(`/simulations?projectId=${encodeURIComponent(projectId)}`),
  optimizations:(projectId='urban-e04')=>request(`/optimizations?projectId=${encodeURIComponent(projectId)}`),
  optimize:body=>request('/optimizations',{method:'POST',body:JSON.stringify({sampleSize:250,seed:42,...body})}),
  promoteOptimization:(runId,candidateId)=>request(`/optimizations/${runId}/candidates/${candidateId}/promote`,{method:'POST',body:'{}'}),
  goals:(projectId='urban-e04')=>request(`/goals?projectId=${projectId}`),
  requirements:(projectId='urban-e04')=>request(`/requirements?projectId=${encodeURIComponent(projectId)}`),
  createRequirementDrafts:(text,projectId='urban-e04')=>request('/requirements/drafts',{method:'POST',body:JSON.stringify({text,projectId})}),
  approveRequirement:id=>request(`/requirements/${id}/approve`,{method:'PATCH',body:'{}'}),
  reviseRequirement:(id,patch)=>request(`/requirements/${id}/revisions`,{method:'POST',body:JSON.stringify(patch)}),
  verifyRequirement:(id,status,evidenceId)=>request(`/requirements/${id}/verification`,{method:'PATCH',body:JSON.stringify({status,evidenceId})}),
  requirementBaselines:(projectId='urban-e04')=>request(`/requirement-baselines?projectId=${encodeURIComponent(projectId)}`),
  createRequirementBaseline:(requirementIds,projectId='urban-e04')=>request('/requirement-baselines',{method:'POST',body:JSON.stringify({projectId,requirementIds})}),
  verificationTasks:(projectId='urban-e04')=>request(`/verification-tasks?projectId=${encodeURIComponent(projectId)}`),
  loops:(projectId='urban-e04')=>request(`/loops?projectId=${encodeURIComponent(projectId)}`),
  stepLoop:id=>request(`/loops/${id}/step`,{method:'POST',body:'{}'}),
  projectState:(projectId='urban-e04')=>request(`/projects/${projectId}/state`),
  completion:(projectId='urban-e04')=>request(`/projects/${projectId}/completion`),
  telemetryLatest:(projectId='urban-e04',vehicleId='PROTO-02')=>request(`/telemetry/latest?projectId=${encodeURIComponent(projectId)}&vehicleId=${encodeURIComponent(vehicleId)}`),
  telemetryStreams:()=>request('/telemetry/streams'),
  calibrations:(projectId='urban-e04')=>request(`/calibrations?projectId=${encodeURIComponent(projectId)}`),
  physicalTests:(projectId='urban-e04')=>request(`/physical-tests?projectId=${encodeURIComponent(projectId)}`),
  recordPhysicalTest:body=>request('/physical-tests',{method:'POST',body:JSON.stringify(body)}),
  approvals:()=>request('/approvals'),
  createApproval:body=>request('/approvals',{method:'POST',body:JSON.stringify(body)}),
  decideApproval:(id,status,comment='')=>request(`/approvals/${id}`,{method:'PATCH',body:JSON.stringify({status,comment})}),
  robotCells:()=>request('/robot/cells'),
  robotCommands:()=>request('/robot/commands'),
  robotAction:body=>request('/robot/actions',{method:'POST',headers:{'Idempotency-Key':body.idempotencyKey},body:JSON.stringify(body)}),
  robotAck:(id,status='completed',result={pass:true})=>request(`/robot/commands/${id}/ack`,{method:'POST',body:JSON.stringify({status,result})}),
  robotInterlocks:(cellId,interlocks)=>request(`/robot/cells/${cellId}/interlocks`,{method:'POST',body:JSON.stringify({interlocks})}),
  robotEmergencyStop:(cellId,reason='operator_emergency_stop')=>request(`/robot/cells/${cellId}/emergency-stop`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({reason})}),
  notifications:(unread=false)=>request(`/notifications${unread?'?unread=true':''}`),
  markNotification:id=>request(`/notifications/${id}/read`,{method:'PATCH',body:'{}'}),
  manufacturingEvaluate:body=>request('/manufacturing/evaluate',{method:'POST',body:JSON.stringify(body)}),
  bom:(projectId='urban-e04')=>request(`/bom?projectId=${encodeURIComponent(projectId)}`),
  suppliers:()=>request('/suppliers'),
  manufacturingEvaluations:()=>request('/manufacturing/evaluations'),
  complianceAssessments:(projectId,designId)=>request(`/compliance/assessments?projectId=${encodeURIComponent(projectId)}${designId?`&designId=${encodeURIComponent(designId)}`:''}`),
  assessCompliance:(projectId,designId)=>request('/compliance/assess',{method:'POST',body:JSON.stringify({projectId,designId})}),
  improvements:()=>request('/improvements'),
  releases:()=>request('/platform/releases'),
  advanceImprovement:(id,action,evidence={})=>request(`/improvements/${id}/advance`,{method:'POST',body:JSON.stringify({action,evidence})}),
  reportUrl:(projectId='urban-e04')=>`/api/reports/${projectId}`
};
